### ISSUE TITLE
[6412bfc7] Magisk closes Play Store and don't execute LiveBoot

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [topjohnwu/Magisk#1088]
After switch to Magisk Canary Build 6412bfc7 I get all the time the msg that Play Store got closed and I don't have LiveBoot (app) anymore at boot.
[2019-02-16_09.12-Magisk.zip](https://github.com/topjohnwu/Magisk/files/2871734/2019-02-16_09.12-Magisk.zip)

**Comment by Didgeridoohan** [comment]
What does your Hide list look like (it should consist of the minimum amount of apps that detect root, nothing else)? And there's no Magisk log...

**Comment by Tobias-B-Besemer** [comment]
The list/log was created with the default settings of the app "SysLog". But I will attach a other log and the Magisk log, soon...

**Comment by Tobias-B-Besemer** [comment]
[magisk.log](https://github.com/topjohnwu/Magisk/files/2871811/magisk.log)
[2019-02-16_11.16-Magisk.zip](https://github.com/topjohnwu/Magisk/files/2871812/2019-02-16_11.16-Magisk.zip)

**Comment by Tobias-B-Besemer** [comment]
Now I get it! No, I hide no app with Magisk!

**Comment by topjohnwu** [comment]
This should fix it: 692f893e1f1659295e4172158dd66c1c9c43b7ec

**Comment by Tobias-B-Besemer** [comment]
Latest version still don't fix the issue!
Seems to get better (less error msgs), but e.g. Play Store still crashes!
[2019-02-25_05.34-Magisk.zip](https://github.com/topjohnwu/Magisk/files/2899070/2019-02-25_05.34-Magisk.zip)
[magisk_2019-02-15.log](https://github.com/topjohnwu/Magisk/files/2899071/magisk_2019-02-15.log)

**Comment by Tobias-B-Besemer** [comment]
I still have this issue with Magisk 18110... :-/

**Comment by Tobias-B-Besemer** [comment]
I still have this issue with v18112...

I just want to know if you still have this issue on your "radar", or if it is really "solved" for you?
