### ISSUE TITLE
Recent MagiskManager Canary release crashes on launch

### ISSUE THREAD

**Issue by DenyDarko** [topjohnwu/Magisk#1155]
**EDIT: CHECK FIRST COMMENT.**

Hey @topjohnwu

Latest Canary is crashing on launch:

Other users on XDA Canary thread confirm it too.

OnePlus6 on OB13

FATAL EXCEPTION: main
Process: com.CPNEH9FSPpGGRP.M, PID: 29119
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.CPNEH9FSPpGGRP.M/a.b}: java.lang.NullPointerException: Attempt to invoke virtual method 'void a.fy.a()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3056)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3191)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1920)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6912)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void a.fy.a()' on a null object reference
	at a.gk.setBackgroundDrawable(Unknown Source:5)
	at android.view.View.setBackground(View.java:21652)
	at android.view.View.<init>(View.java:5551)
	at android.widget.ImageView.<init>(ImageView.java:177)
	at android.widget.ImageButton.<init>(ImageButton.java:86)
	at android.widget.ImageButton.<init>(ImageButton.java:82)
	at a.gk.<init>(Unknown Source:4)
	at androidx.appcompat.widget.Toolbar.p(Unknown Source:14)
	at androidx.appcompat.widget.Toolbar.a(Unknown Source:0)
	at a.jj.<init>(Unknown Source:394)
	at a.jj.<init>(Unknown Source:1)
	at a.bn.<init>(Unknown Source:27)
	at a.aq.a(Unknown Source:37)
	at a.an.a(Unknown Source:4)
	at a.bal.onCreate(Unknown Source:46)
	at android.app.Activity.performCreate(Activity.java:7149)
	at android.app.Activity.performCreate(Activity.java:7140)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3031)
	... 11 more

**Comment by IdanHo** [comment]
It seems topjohnwu has realised this and updated the magisk canary app with the build error fix, unfortunately, it seemes some people including me and you downloaded the app just at the right time to get the broken version, i fixed it by just downloading the fixed version directly and updating manually. (over at https://raw.githubusercontent.com/topjohnwu/magisk_files/master/canary_builds/app-full-release.apk)

**Comment by DenyDarko** [comment]
Thanks for the headsup @IdanHo .

I'm leaving this open so if someone's on the same situation will see your comment :)

**Comment by martyfender** [comment]
Even with the updated version, MM still crashes for many of us when trying to access the hide list. I posted logs in the Canary thread. The latest unofficial build also crashes, on 3 devices and the 2 devices I have Canary on.

They are all, Nextbook Ares 8A's, x86, Android 6.0.1 tablets.

Thanks
