### ISSUE TITLE
mounting binaries to /bin makes device stuck at boot logo

### ISSUE THREAD

**Issue by laggardkernel** [topjohnwu/Magisk#18]
I just mention this problem in #17 . After adding binaries in the module, the device stuck at the boot logo, I'm sure it's boot logo this time, not the animation. I remember the days on v6 mounting binaries worked well for me, but it has been broken since v7.
As I said,

> According to the magisk.log, everything worked well and ended with late_start service mode running. 

I will attach all the logs i find in /cache, wish it will help you figure out the trouble. There is some binaries in the /magisk/v4a/system/bin directory.

[mount_bin_err.zip](https://github.com/topjohnwu/Magisk/files/618505/mount_bin_err.zip)

Tested on OnePlus3, OxygenOS 3.2.7, Marshmallow 6.0.1. Magisk v9 commit 670fe85 + phh's superuser.

**Comment by laggardkernel** [comment]
Commit c07e9ac fixed the problem of mounting files to /bin. But I stuck at **boot animation** with a module including **frameworks**, files like ```/system/framework/*.jar```. Mounting frameworks works well before this commitment. @topjohnwu 

Besides, I found out this problem with only Magisk + phh's superuser, Xposed and some test frameworks installed. I also stuck at **boot logo** once with all my daily Magisk modules installed.  I guess there is some other module causing the boot logo stuck. I will try to get more detail by testing the modules one by one later sometime.

Anyway, there's much improvement on the magisk_mask.sh thesedays. We all appreciate your hardwork behind it. Take your time.

**Comment by topjohnwu** [comment]
All issues are fixed in the massive refactors (c07e9ac29d84ac01c7cd4e049d9cc39b6b7f6f88 and 1e3586621b982f90bd50a2a7113be78455fe4153)

**Comment by laggardkernel** [comment]
I tried all the commitments you submitted yesterday. With the latest commit c9157cc, I still encountered boot logo stuck. I removed binaries in the mod, bit no magic happened. Maybe it's related to replacing existing apps, I will try to dig deeper.

**Comment by ljani** [comment]
I had problems with `/system/framework/*.jar` files at [`v9`](https://github.com/topjohnwu/Magisk/tree/v9) too, but they seem to work as of [`b2431b9`](https://github.com/topjohnwu/Magisk/tree/b2431b982f58ed19143fe2fde7977149ecfc06de). (S7E, stock 6.0.1.) Many thanks.
