### ISSUE TITLE
vbmeta error still persistent

### ISSUE THREAD

**Issue by alexn9630** [topjohnwu/Magisk#2136]
Hello, 
I'm not too sure what is going on but Magisk 20.1 still causes vbmeta error on A20e
Please help me out
Thanks

**Comment by martyfender** [comment]
Try the latest Canary debug build.

**Comment by alexn9630** [comment]
> Try the latest Canary debug build.

Yeah nah, doesnt work m8

**Comment by martyfender** [comment]
Is it the same error as in #1961?

**Comment by alexn9630** [comment]
> Is it the same error as in #1961?

Yes it is

**Comment by topjohnwu** [comment]
It should already be fixed, please start with a clean ODIN restore to make sure your device is bootable in the first place

**Comment by yakov116** [comment]
@topjohnwu I am having the same issue. I also tried with the latest. Gave up on rooting...

**Comment by alexn9630** [comment]
> It should already be fixed, please start with a clean ODIN restore to make sure your device is bootable in the first place

I swear its still persistent. I cannot boot into the factory reset thing. I did flash the phone with the stock firmware and it works fine. Please help.

**Comment by thecyberd3m0n** [comment]
Samsung SM-T515, same issue. Trying "TWRP way". Unrooted Android is total s***

**Comment by ahronshor** [comment]
[here in xda](https://forum.xda-developers.com/showpost.php?p=81596083&postcount=14) is a full tread about this issue for a51.

But the solution to make a signed recovery for each device is not so good for magisk.
Note that the same problem was also found in note 10 lite n770f,
And probably that's what will happen even in many new Samsung models...
