### ISSUE TITLE
After "Hide Magisk Manager", app keeps prompting to upgrade to full Magisk Manager

### ISSUE THREAD

**Issue by jchia** [topjohnwu/Magisk#2211]
I'm using Magisk 20.2 (20200) and Magisk Manager 7.5.0 (265) on an Android 10 device.

After I use "Hide Magisk Manager" to rename the app to "Manager", the renamed app when started prompts "Upgrade to full Magisk Manager to finish the setup. Download and install?" If I select "cancel', it exits. If I select "OK", it repeats the prompt.

It should just start normally instead of prompting in a loop.

**Comment by tardeaux** [comment]
I had the same issue when trying to reinstall Magisk Manager. I was able to work around it by uninstalling, reinstalling Manager 7.3.5 (from releases page), using that version to repackage, and then updating to 7.5.0.

**Comment by ElDavoo** [comment]
Same issue on a Redmi 8 with Pie.

**Comment by Didgeridoohan** [comment]
If reporting about issues, don't do "workarounds"... Reproduce the issue while grabbing a logcat so that @topjohnwu has something to work with!

No log, no fix...

**Comment by virgo7120** [comment]
I'm using Magisk 20.2 (20200) and Magisk Manager 7.5.0 (265) on an Android 9 device.

After I use "Hide Magisk Manager" to rename the app to "Manager", the renamed app when started prompts "Upgrade to full Magisk Manager to finish the setup. Download and install?" If I select "cancel', it exits. If I select "OK", it repeats the prompt.

**Comment by Senliast** [comment]
I can confirm, have the same issue. Latest Magisk Stable, Android 9. Logcat: https://gofile.io/?c=iOHzr1

**Comment by topjohnwu** [comment]
@Senliast thanks for the logs, here is the relevant line regarding this issue
`01-04 22:01:50.048  5095  5095 D ziparchive: Zip: EOCD not found, /data/user_de/0/com.B.skGn.IaN7.isam/dyn/current.apk is not zip`

**Comment by virgo7120** [comment]
@topjohnwu , what does it mean? What is the answer?

**Comment by Senliast** [comment]
@topjohnwu no problem

**Comment by distante** [comment]
Good to know I am not the only one with this problem. I will also try to make a raw of my logcat in the morning.

**Comment by tlxxxsracer** [comment]
Same issue here as well. Tried to downgrade to the previous Magisk stable and still the same issue

**Comment by virgo7120** [comment]
The previous version does not work either (Asus Max pro M2 Android 9)

**Comment by virgo7120** [comment]
On Lineage os 17 it is the same :-(

**Comment by ivan-aksamentov** [comment]
I tried to roll-back on canary channel and here is what works for me on Lineage 17.0 (Q):
Canary from Dec 5, 2019: Magisk `20.2-11b7076a` / Magisk Manager `7.4.1-291c718b` ([da34d45](https://github.com/topjohnwu/magisk_files/tree/da34d45b111af268bc493a73d628e8510f74c258) in `magisk_files`).

## Instructions

The following instructions describe how to roll back your Magisk to v20.2-11b7076a and Magisk Manager to v7.4.1-291c718b, both are canary-quality snapshots.

Please note that canary snapshots are of much lower quality than typical releases. You should take the above disclaimers seriously. You are discouraged to try these instructions if Magisk and Magisk Manager work satisfactory for your needs already.


```
THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN 
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

```
 /*
 * Your warranty is now void.
 *
 * I am not responsible for bricked devices, dead SD cards,
 * thermonuclear war, or you getting fired because the alarm app failed. Please
 * do some research if you have any concerns about features included in this ROM
 * before flashing it! YOU are choosing to make these modifications, and if
 * you point the finger at me for messing up your device, I will laugh at you.
 */
 ```


 - Uninstall Magisk Manager and hidden Magisk Manager apps.
 - Download [app-release.apk](https://raw.githubusercontent.com/topjohnwu/magisk_files/da34d45b111af268bc493a73d628e8510f74c258/app-release.apk) and [magisk-release.zip](https://raw.githubusercontent.com/topjohnwu/magisk_files/da34d45b111af268bc493a73d628e8510f74c258/magisk-release.zip) from `magisk_files` here:
https://github.com/topjohnwu/magisk_files/tree/da34d45b111af268bc493a73d628e8510f74c258
 - Flash downloaded zip file with TWRP
 - Boot the OS and open Magisk Manager. Main screen will offer updates. Do not update!
 - (optional) If upon first run Magisk Manager says that Magisk is not installed, then uninstall all instances of Magisk Manager, reinstall from apk downloaded from `magisk_files` repo and open the app. 
 - Verify on main screen that the "Installed:" version of Magisk is `20.2-11b7076a` and  the "Installed:" version of Magisk Manager is `7.4.1-291c718b`.
 - Now that you have the correct versions, go to settings and disable "Check updates".
 - Optionally, change the "Update channel" to whatever fits your needs.
 - Tap "Hide Magisk Manager" in settings, rename. Open the renamed app. When offered to Upgrade to full Magisk Manager, tap "OK".
 - That should work as long as you don't upgrade to "broken" versions.
 - In the future, when this will be fixed, you may want to upgrade to the fixed version. Now that the updates are disabled, you can monitor new canary versions manually in the Magisk Manager: pull down on main screen, or monitor the commit history of `magisk_files`: https://github.com/topjohnwu/magisk_files/commits/canary
 You can check new stable releases on "Releases" page: https://github.com/topjohnwu/Magisk/releases and/or set to "Watch" this repository for email notifications.

You can download manually from the `magisk_files` repo above, or here are the downloading commands, for convenience:
```bash
curl -fsSL "https://raw.githubusercontent.com/topjohnwu/magisk_files/da34d45b111af268bc493a73d628e8510f74c258/app-release.apk" -o "MagiskManager-v7.4.1-291c718b.apk"

curl -fsSL "https://raw.githubusercontent.com/topjohnwu/magisk_files/da34d45b111af268bc493a73d628e8510f74c258/magisk-release.zip" -o "Magisk-v20.2-11b7076a.zip"


```

## See also

More about canary channel on XDA: https://forum.xda-developers.com/apps/magisk/dev-magisk-canary-channel-bleeding-edge-t3839337

**Comment by raghu46j** [comment]
Even i have same issue in OP6T & RN5 Pro
[https://gofile.io/?c=mXt6Nu](url)

**Comment by avrelaun** [comment]
Same issue here, Android 10, same log `current.apk is not zip`

**Comment by lizr2004** [comment]
Same issue on OnePlus 6, lineage os 17. Magisk Manager 7.5.
[current.apk](http://fars.ee/LG-0.apk)
[logcat(clip)](http://fars.ee/0Nlo)

**Comment by lss4** [comment]
I remember seeing similar issue on v20.1 (and its corresponding Magisk Manager version). However, at that version, while it first asked me to upgrade to full Magisk Manager, pressing OK will enter the main screen and it never asked me again.

From what I remember, the issue is not present in earlier versions. Also, tardeaux's comment is probably correct as I'm currently on Magisk Manager 7.5.0, but the repacking was done on earlier versions, and it still works after upgrading to 7.5.0.

So it's probably an existing bug/regression that's been regressed even further. I couldn't test v20.2 at present, as it currently doesn't boot on my device.

I suspect the app renaming feature might have some issues as this time I renamed the Magisk Manager to something else that doesn't contain either `Magisk` or `Manager`, so this might have confused it.

**Comment by topjohnwu** [comment]
I figured out the culprit, the stub APK is now updated and this issue should be fixed

**Comment by Si1viu** [comment]
Tested succesfully, renaming Magisk works, the app starts afterwards and also the banking app no longer detects Magisk after the rename

**Comment by raghu46j** [comment]
Issue is fixed, thanks John.

**Comment by virgo7120** [comment]
Issue is fixed, thanks John. Jesteś wielki, Polska się kłania :)

**Comment by davex2012** [comment]
@topjohnwu got same error keeps prompting to upgrade to full Magisk Manager. V 20.3 and latest apk.
[magisk_log_20200131_154417.log](https://github.com/topjohnwu/Magisk/files/4139975/magisk_log_20200131_154417.log)

**Comment by jthreja** [comment]
I am still facing the same issue. Tested on latest stable and the new canary build too.

**Comment by CooperTUGA** [comment]
i am with the same issue...

**Comment by jchia** [comment]
@jthreja @CooperTUGA Since the issue has already been solved for others, it's not clear to me how the issue you are facing can be addressed without further information. Perhaps it would help to provide logs.

**Comment by sutidor** [comment]
Same issue here, when repackaging the App I get prompted for full install. I am using OP7p, latest android 10, current.apk (canary build), magisk 20.4.

My log is empty for some reason so posting it does not make much sense.
Without hiding and repackaging magisk manager works like a charm

**Comment by TheOriginalGregToo** [comment]
For anyone who might need the solution in the future, I found a workaround.  Changing the default "manager" name allowed me to successfully rename and hide magisk manager.  Best of luck!

**Comment by tomrennen** [comment]
I found myself in the same situation (OP7T, OOS 10, Magisk Manager 8.0.7 and magisk 20.4) where renaming was failing. The following worked for me:

1. Uninstall Magisk Manager 8.0.7 (latest)
2. Install Magisk Manager 7.3.5 (from releases page on GitHub)
3. Rename Magisk Manager 7.3.5 from within Magisk Manager
4. Undo rename, this will automatically update to latest (8.0.7 for me)
5. Rename Magisk Manager 8.0.7 from within Magisk Manager
6. It magically worked this time.

**Comment by ProblematicDude** [comment]
Same issue with magisk hide. Now when I'm clicking stub apk. It prompt me with above error. I guess re-install is the only way.

**Comment by Xinetizen** [comment]
> I found myself in the same situation (OP7T, OOS 10, Magisk Manager 8.0.7 and magisk 20.4) where renaming was failing. The following worked for me:
> 
> 1. Uninstall Magisk Manager 8.0.7 (latest)
> 2. Install Magisk Manager 7.3.5 (from releases page on GitHub)
> 3. Rename Magisk Manager 7.3.5 from within Magisk Manager
> 4. Undo rename, this will automatically update to latest (8.0.7 for me)
> 5. Rename Magisk Manager 8.0.7 from within Magisk Manager
> 6. It magically worked this time.

This actually worked .
Was running latest build (21.4 and 8.0.7) on OnePlus7 (guacamoleb) (Android 10)

**Comment by sumsarz** [comment]
> I found myself in the same situation (OP7T, OOS 10, Magisk Manager 8.0.7 and magisk 20.4) where renaming was failing. The following worked for me:
> 
> 1. Uninstall Magisk Manager 8.0.7 (latest)
> 2. Install Magisk Manager 7.3.5 (from releases page on GitHub)
> 3. Rename Magisk Manager 7.3.5 from within Magisk Manager
> 4. Undo rename, this will automatically update to latest (8.0.7 for me)
> 5. Rename Magisk Manager 8.0.7 from within Magisk Manager
> 6. It magically worked this time.

This just worked for me too, after getting the update error on a hidden Magisk Manager setup.

Can be noted that it happened after I clicked the "Update Magisk Manager" notification, instead of doing it from within the app like I usually do. Not sure if that's why, or it was just a coincidence.

**Comment by lss4** [comment]
> This just worked for me too, after getting the update error on a hidden Magisk Manager setup.
> 
> Can be noted that it happened after I clicked the "Update Magisk Manager" notification, instead of doing it from within the app like I usually do. Not sure if that's why, or it was just a coincidence.

When the Manager is not hidden, upgrading is straightforward.

For a hidden Manager, the process might be a bit complicated that we need to take a deeper look at.

**Comment by Masck01** [comment]
> I found myself in the same situation (OP7T, OOS 10, Magisk Manager 8.0.7 and magisk 20.4) where renaming was failing. The following worked for me:
> 
> 1. Uninstall Magisk Manager 8.0.7 (latest)
> 2. Install Magisk Manager 7.3.5 (from releases page on GitHub)
> 3. Rename Magisk Manager 7.3.5 from within Magisk Manager
> 4. Undo rename, this will automatically update to latest (8.0.7 for me)
> 5. Rename Magisk Manager 8.0.7 from within Magisk Manager
> 6. It magically worked this time.

I just uninstalled renamed apk and then re install magisk manager 7.3.5. No further steps needed, after I can update app plus manager to v22
