### ISSUE TITLE
Graphic glitch when installing modules

### ISSUE THREAD

**Issue by Alexey71** [topjohnwu/Magisk#2506]
Latest Canary app. Android 8.1.0 (Lineage 15.1). Xiaomi Redmi Note 4

![Screenshot_20200301-204453](https://user-images.githubusercontent.com/10572914/75630678-f5634a80-5bfd-11ea-843d-0f9d59e1b5e4.png)
![Screenshot_20200301-204547](https://user-images.githubusercontent.com/10572914/75630679-f72d0e00-5bfd-11ea-81f4-07dc8e788fec.png)

**Comment by KaMyKaSii** [comment]
I have suffered from this bug since the first build of the Magisk Manager redesign. After the last build, with a commit in an attempt to solve this, the problem was solved 99% when the Manager himself creates the text on the screen but when the scrolling is done manually the glitch comes back. My Magisk Manager package name is com.I.u.Vz.omERDIsPQ if necessary.
https://sendvid.com/i0bo9l2g
[screen.txt](https://github.com/topjohnwu/Magisk/files/4272660/screen.txt)

**Comment by Alexey71** [comment]
This bug is also from the new application design. I saw here they someone were already opening a bug with the same problem. The developer closed issues, allegedly fixed. But nothing has changed for me, it's still a problem.

**Comment by Alexey71** [comment]
New canary magisk manager 72f6770d - not fixed
[LogCat.txt](https://github.com/topjohnwu/Magisk/files/4334055/LogCat.txt)



![Uploading Screenshot_20200315-134831.png…]()

**Comment by osm0sis** [comment]
@diareuse, thoughts? Any logs that would be helpful?

**Comment by topjohnwu** [comment]
@osm0sis I'll rewrite the console screen, just didn't got the time yet

**Comment by diareuse** [comment]
That's absolutely unnecessary for this issue alone. The screen still has animations enabled, those need to be disabled completely and this will get fixed 🙂

**Comment by topjohnwu** [comment]
@diareuse if you said so, then try to fix it :D

**Comment by xerta555** [comment]
@diareuse I have also glitchs on modules installs and on Magisk flashs (Magisk/Manager update)
[logcat.txt](https://github.com/topjohnwu/Magisk/files/4356520/logcat.txt)
[logcat2.txt](https://github.com/topjohnwu/Magisk/files/4356521/logcat2.txt)
[logcat_next.txt](https://github.com/topjohnwu/Magisk/files/4356523/logcat_next.txt)
![Screenshot_20200319-135710](https://user-images.githubusercontent.com/20888017/77105603-34770580-6a1e-11ea-8e95-980e2f8d4f5c.png)

And I'm just pointing out that i have test on the last Canary version.

**Comment by Alexey71** [comment]
It’s even worse with the latest version, now everywhere

![Screenshot_20200328-132301](https://user-images.githubusercontent.com/10572914/77821119-c3f47680-70f8-11ea-9aed-58939a3732dc.png)
![Screenshot_20200328-133120](https://user-images.githubusercontent.com/10572914/77821121-c525a380-70f8-11ea-8b94-a108c7f1d45c.png)
![Screenshot_20200328-133128](https://user-images.githubusercontent.com/10572914/77821122-c5be3a00-70f8-11ea-9d43-e603a941eabf.png)
![Screenshot_20200328-133135](https://user-images.githubusercontent.com/10572914/77821123-c5be3a00-70f8-11ea-9d48-7d60e92ba9aa.png)

**Comment by diareuse** [comment]
At this point, I know for a fact that this is caused by animations. However I wonder how the hell is the AutoAnimation implemented on different systems and devices, if it fucks the UI up this royally.

**Comment by Bob-YsPan** [comment]
> It’s even worse with the latest version, now everywhere
> 
> ![Screenshot_20200328-132301](https://user-images.githubusercontent.com/10572914/77821119-c3f47680-70f8-11ea-9aed-58939a3732dc.png)
> ![Screenshot_20200328-133120](https://user-images.githubusercontent.com/10572914/77821121-c525a380-70f8-11ea-8b94-a108c7f1d45c.png)
> ![Screenshot_20200328-133128](https://user-images.githubusercontent.com/10572914/77821122-c5be3a00-70f8-11ea-9d43-e603a941eabf.png)
> ![Screenshot_20200328-133135](https://user-images.githubusercontent.com/10572914/77821123-c5be3a00-70f8-11ea-9d48-7d60e92ba9aa.png)

I have same problem on latest 279 version
![Screenshot_20200328-233153](https://user-images.githubusercontent.com/46966555/77826830-d13b5080-714c-11ea-9a6f-5ffb35a98d34.png)

**Comment by xerta555** [comment]
On my Nougat device with custom ROM, with last Canary and last Manager, i get glitchs on all screens of the app, even on flashs screens:
[logcat1.txt](https://github.com/topjohnwu/Magisk/files/4397581/logcat1.txt)
[logcat2.txt](https://github.com/topjohnwu/Magisk/files/4397582/logcat2.txt)

A folder wich contain the screens:
https://drive.google.com/drive/folders/1SaTatr2K36Dp2Xl35G6o0RI-rl_6uJ92

I hope that u could quickly fix theses glitchs @diareuse ....

**Comment by topjohnwu** [comment]
Consolidate to #2598 as further investigation points out these 2 issues are related

**Comment by xerta555** [comment]
> Consolidate to #2598 as further investigation points out these 2 issues are related

I have see your Twitter post related to this major UI issue, just for informations, my device run on Android 7.1.2 Resurection Remix (custom ROM).

**Comment by Alexey71** [comment]
Yeah latest Canary Fixed!!! Thx

**Comment by xerta555** [comment]
> Yeah latest Canary Fixed!!! Thx

For me too 👍
