### ISSUE TITLE
Magisk canary 122b4d6 will break OP7T + OP8/8Pro fingerprint unlock

### ISSUE THREAD

**Issue by sabpprook** [topjohnwu/Magisk#2803]
OnePlus 7T HD1900 OOS India 10.3.2.HD65AA

It only happened on https://github.com/topjohnwu/Magisk/commit/122b4d66b62db2ff6d5c6aa02933c33f121217d2, previous build https://github.com/topjohnwu/Magisk/commit/a62bdc58cb2e06128b82d332ba1f4e72f5700269 works fine.
I'm not able to get logcat right now, sorry for this.

**Comment by osm0sis** [comment]
Can confirm. More likely it's caused by https://github.com/topjohnwu/Magisk/commit/6a2e781db29a13e9fad5fead2242115d648736e4, which is similar to custom kernels before this https://github.com/engstk/op7/commit/c8b1bcf78787b83a3c87a910c5713ebb9c523afd

I know it seems to be fine when set later in boot so I'll see if there's a way to fix that without just removing it entirely.

**Comment by sabpprook** [comment]
After some quick test, the latest canary build will lead fingerprint scan to fast that unable to detect whole fingerprint. Can not figure out why this will happen

**Comment by osm0sis** [comment]
Here's a workaround script for now:

/data/adb/service.d/verifiedboot-fix.sh:
```
#!/system/bin/sh

# Magisk service.d script
resetprop vendor.boot.verifiedbootstate orange
until [ "$(getprop sys.boot_completed)" == 1 ]; do
  sleep 1
done
resetprop vendor.boot.verifiedbootstate green

```

**Comment by sabpprook** [comment]
Problem sorted!

Due to this issue, maybe the codes of props fix will move to boot_complete to avoid this?

**Comment by osm0sis** [comment]
Just that prop needs to move. Best to leave the others as early as possible.

**Comment by Chartman123** [comment]
Seems to affect OnePlus 8, too. Can't use my fp sensor since I've installed the latest canary update.

**Comment by osm0sis** [comment]
MagiskHide runs as soon as module post-fs-data scripts and system props are done, doing hide_sensitive_props(). Using service.d to flip it back to orange in my workaround might just be too late on the OP8, but the solution would still be the same.

What we'll need to avoid removing vendor.boot.verifiedbootstate entirely is a separate hide_sensitive_props_late() which runs at sys.boot_completed like my script above.

**Comment by sabpprook** [comment]
A quick fix https://github.com/sabpprook/Magisk/commit/e71bdb499c0df83477f48ccdf920805ccbffc457

**Comment by osm0sis** [comment]
That's pretty much what I had in mind, actually, nice job! Open a PR?

**Comment by ekka1993** [comment]
Will this fix the fingerprint error on oneplus 8 pro ? With magisk 20.4?

**Comment by osm0sis** [comment]
@ekka1993 This has nothing to do with 20.4, it's only broken in Canary 20411.

**Comment by osm0sis** [comment]
Ah, looks like @topjohnwu also took a crack at it: https://github.com/topjohnwu/Magisk/commit/97db49a57bab9fc573eee861b59bed95dfd5812a

**Comment by ekka1993** [comment]
Is it solved?

**Comment by osm0sis** [comment]
Yep, working again on my 7T in 20412. :+1:

It stays reporting orange though due to a typo I just found and let @topjohnwu know about. That should be fixed for 20413.

**Comment by bittylicious** [comment]
Sadly 20412 isn't working here on my OnePlus 8.

I still get the "Fingerprint hardware not accessible" error on the lock screen. This is using the latest OnePlus release for the Europe variant, 10.5.6.IN21BA.

I'm not sure if it's related, but SafetyNet fails too even with MagiskHide on (ctsProfile fails, basicIntegrity is fine). It worked with 10.5.5.IN21BA but I can't confirm which version of Magisk Canary I was on then. I'm aware you don't generally investigate SafetyNet with canary releases though.

**Comment by fuxdafuzz12** [comment]
Can someone help me with flashing Magisk using termux on an Android Lg
stylo 5. I have accessed root using Ubuntu-andronix anyonw have
instructions on this issue. I'm new to this but learn very fast. Someone
help please!

**Comment by osm0sis** [comment]
@bittylicious can you clarify if 20411 was where this issue started for you? If you didn't try 20411 then please try 20410 and let me know.

**Comment by bittylicious** [comment]
@osm0sis It definitely was not working with 20411. I can't easily confirm whether it was the upgrade to 20411 that caused it to fail, or the Android update to 10.5.6.

I sadly don't have a build environment to prepare specific releases. Is there an easy way for me to try 20409, e.g. if you can provide me with a custom channel URL or something like that?

Ignore the SafetyNet error - disabling all modules enables SafetyNet to pass again.

**Comment by osm0sis** [comment]
@bittylicious all Canary releases are contained here: https://github.com/topjohnwu/magisk_files/commits/canary

Simply go back to the commit for 20409 and download the magisk-debug.zip from that commit, then flash it via Manager's Modules page "Install from storage"

**Comment by bittylicious** [comment]
@osm0sis Thanks for the instructions.

I'm now on 20409 but sadly the fingerprint doesn't work, so this issue is probably unrelated. Best guess is that it's the same issue @ekka1993 is experiencing with his OnePlus 8 Pro.

**Comment by osm0sis** [comment]
Does any previous Magisk build work on the 8 Series? Are you using custom kernels?

**Comment by bittylicious** [comment]
@osm0sis Yes, everything was working wonderfully before, fingerprint, SafetyNet, the lot. It was beautiful. No custom kernels.

Based on the Canary timestamps, I think it's the Android upgrade which cased things to break, not any change made in Magisk. Most likely the Android upgrade has introduced some sort of incompatibility with Magisk though.

**Comment by osm0sis** [comment]
@bittylicious And you aren't using my workaround script, presumably?

**Comment by ekka1993** [comment]
Mine worked with 10.5.8 then i restored with brick tools then i stopp worked.
I removed magisk then mine phone got soft bricked  So i hade to restore it with bricked tools. Then i stopp worked.

**Comment by bittylicious** [comment]
@osm0sis No, I'm not using anything apart from Canary versions. No extra scripts.

**Comment by osm0sis** [comment]
Sounds sort of unrelated then, especially where ekka mentioned 20.4 stable and you say 20409 still doesn't work.

**Comment by Chartman123** [comment]
> Does any previous Magisk build work on the 8 Series? Are you using custom kernels?
> 
> @Chartman123 you reported it happened with 20411 on your 8, can you update us on whether 20412 fixes it for your setup?

I've just installed the update and rebooted: the fp sensor is working fine again. At the moment I still have your script in the service.d directory...

**Comment by osm0sis** [comment]
Alright, @Chartman123's confirmation suggests the original issue from this thread is resolved.

Those of you still having issues will need to look into that further and open a new issue if appropriate. Be sure to include last working Magisk build, test stable and canary, and try with MagiskHide off and on.

**Comment by sabpprook** [comment]
@bittylicious How about adding fingerprint service into magiskhide list?

**Comment by ekka1993** [comment]
Turn magisk hide off dosent work, same resultat. Error fp registration

**Comment by bittylicious** [comment]
@Chartman123 Can you confirm what version of the Android software you're using? Is it the latest OnePlus software for your OnePlus 8?

@sabpprook Sadly no different. "Fingerprint hardware not available" still.

**Comment by ekka1993** [comment]
Where do i download 20412?

**Comment by bittylicious** [comment]
@ekka1993 Change your settings Update Channel to Canary. It's the latest Canary version.

**Comment by osm0sis** [comment]
If turning MagiskHide off doesn't help then the latest Canary won't make a difference either, unfortunately.

**Comment by ekka1993** [comment]
I Still have 20400 hmm

**Comment by osm0sis** [comment]
Yeah, so @ekka1993, when did it work last?

**Comment by ekka1993** [comment]
I have 10.5.8

**Comment by ekka1993** [comment]
It worked on 10.5.8 turn i bricked mine phone and i restored it then i stop to work

**Comment by bittylicious** [comment]
FYI, 10.5.8 is the latest update for the 8 Pro. It will include similar patches to 10.5.6, the latest version on the 8.  So, me and @ekka1993 are likely experiencing the same error if it stopped working after the latest Android update for him.

If @Chartman123 can confirm he's not yet on the latest Android/OnePlus version, this puts together quite a clear picture. If he is on 10.5.6 (8) or 10.5.8 (8 Pro), then who knows!

**Comment by osm0sis** [comment]
ekka was already on latest and had it working, then it broke after bricking the device and using some tools to recover it. Sounds like they were on 10.5.8 and Magisk 20.4(20400) stable both when working and broken.

**Comment by Chartman123** [comment]
I'm on 10.5.4 European version, the latest that is offered to me in the updater

**Comment by osm0sis** [comment]
@bittylicious have you tried rebooting with MagiskHide off yet to rule out some further interaction there?

**Comment by bittylicious** [comment]
@osm0sis Yes tried that, doesn't make a difference here.

@Chartman123 Interesting. You should get 10.5.6 soon with a bit of luck. I would have suggested using the OnePlus downloads page but it doesn't appear to be on there yet, so maybe they've spotted issues with the OTA update? Let us know when it comes please.

**Comment by zyonee** [comment]
The latest canary has the fingerprint reader working on my OP8 Pro with OOS 10.5.8. Not sure if it matters, but it's the European version. Went directly from canary a62bdc58 to 99ef2062. I did try 122b4d66 yesterday with the fingerprint reader not working, but for me the latest canary fixed the issue. Good work!

**Comment by ekka1993** [comment]
Should i use direct update ? do i need to patch it and install with adb ?

**Comment by 0xCCD** [comment]
> Mine worked with 10.5.8 then i restored with brick tools then i stopp worked.
> I removed magisk then mine phone got soft bricked So i hade to restore it with bricked tools. Then i stopp worked.

I had the same issue, in my case downgrade to v20.4 solved it and new canary also. But on  oneplus forums they talk also about the fact that a fastboot flash will damage one partition which is related for the fingerprint 

https://forums.oneplus.com/threads/enrollment-was-not-completed-fingerprint-registration-error.1218379/

**Comment by osm0sis** [comment]
@sabpprook @Chartman123 @zyonee @0xCCD
The issue is now properly resolved in 20414 with vendor.boot.verifiedbootstate green after 3c04dab47274e9bbbfb3ddd1fcf71c929c8ed0c0. :+1:

**Comment by ekka1993** [comment]
Hey guys, do you have the stock boot img for oneplus 8 pro 10.5.8 Europe (IN11BA) ? 
Did know how to Contact you

**Comment by 0xCCD** [comment]
> Hey guys, do you have the stock boot img for oneplus 8 pro 10.5.8 Europe (IN11BA) ?
> Did know how to Contact you

https://send.firefox.com/download/32475d18c3fc0745/#t93WiF7h3IGEWhzTFola5w

**Comment by ekka1993** [comment]
Is it patched with magisk or stock ?

**Comment by 0xCCD** [comment]
> Is it patched with magisk or stock ?

fresh from OTA on my sdcard, not patched

**Comment by ekka1993** [comment]
Thanks, i Still has problem with fp, i Will try a new boot img IF it Will work

**Comment by ekka1993** [comment]
Is your fp working with 10.5.8 and magisk ?

**Comment by 0xCCD** [comment]
> Thanks, i Still has problem with fp, i Will try a new boot img IF it Will work

check this https://forums.oneplus.com/threads/enrollment-was-not-completed-fingerprint-registration-error.1218379/page-2#post-21617960

**Comment by 0xCCD** [comment]
> Is your fp working with 10.5.8 and magisk ?

Yes it is working but there are two different issues atm with fingerprint one, was caused nby Magisk updtae another is caused while flashing through fastboot

**Comment by ekka1993** [comment]
Flashing with adb, cant be solved right now ? Or am i wrong ?

**Comment by 0xCCD** [comment]
As far as I know you can only solve the issue caused by Magisk, the other issue is caused by a damaged partition which need to get fixed with a software update from Oneplus

**Comment by ekka1993** [comment]
I Will try reflash a new magisk boot img and see IF it works

**Comment by 0xCCD** [comment]
v20.4 and latest canary works fine for me

**Comment by ekka1993** [comment]
Same error so have to wait for oneplus to slove it.

New boot img magisk 20.4 and latest canary. 20414

**Comment by bittylicious** [comment]
I just want to confirm with you that I have this error still, and I never flashed anything from fastboot manually.

My error (which granted is NOT the issue on this issue) came about when I had Canary (probably 20410 or 20411, and then upgraded to the latest OnePlus version (10.5.6 in my region). This would have been a full ROM download, not the OTA patch, so maybe that also involves a flash of other partitions? I'm not sure.

**Comment by 0xCCD** [comment]
> I just want to confirm with you that I have this error still, and I never flashed anything from fastboot manually.
> 
> My error (which granted is NOT the issue on this issue) came about when I had Canary (probably 20410 or 20411, and then upgraded to the latest OnePlus version (10.5.6 in my region). This would have been a full ROM download, not the OTA patch, so maybe that also involves a flash of other partitions? I'm not sure.

I usually also have full rom updates, but as long it is flashed through Local Upgrade functionality of Oxygen OS it should be safe. Probably you can ask on oneplus forum
