### ISSUE TITLE
MagiskHide doesn't work on Moto G 1st (falcon_cdma XT1031)

### ISSUE THREAD

**Issue by rmgrimm** [topjohnwu/Magisk#41]
With Magisk v9, the log would show that MagiskHide was constantly reloading the list, creating a log file several megabytes in size and failing safetynet.

With v10.2, SafetyNet still fails with CTS profile mismatch and the log is now as follows:
[magisk_error_20170107_210727.log.txt](https://github.com/topjohnwu/Magisk/files/691853/magisk_error_20170107_210727.log.txt)

That log is after 87 hours of uptime. If I can provide any other information, please let me know.

**Comment by topjohnwu** [comment]
Should be fixed a while ago

**Comment by rmgrimm** [comment]
Unless you've released a new version past v11.6, it is not fixed. MagiskHide still does not work on Moto G 1st gen. The relevant parts of the log from the original post still remain:

```
Zygote(0) ns=  
```

This line usually shows a blank namespace. Sometimes it'll show the replacement character indicating a missing glyph in the font. (https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character)

Following that, only the first attempt to validate SafetyNet will show:
```
MagiskHide: com.google.android.gms.unstable(PID=3641 ns=[0 3641 10018 com.google.android.gms.unstable service com.google.android.gms/.droidguard.DroidGuardService]
)
```

Once this kind of line is triggered, the log stops getting spammed with reloading the list.

A log from today:
[magisk_error_20170329_161801.log.txt](https://github.com/topjohnwu/Magisk/files/880427/magisk_error_20170329_161801.log.txt)

In this log, I had MagiskHide disabled for regular usage of the phone. Then I turned on usage to try it out. Again, this is with Magisk v11.6 and MagiskManager v4.2.7
