### ISSUE TITLE
Bootloop after upgrade to LineageOS 18.1 (Android 11) on Moto G7 Plus (lake)

### ISSUE THREAD

**Issue by Tutul-** [topjohnwu/Magisk#4213]
Device: Moto G7 Plus (lake)
Android version: LineageOS 18.1 (Android 11)
Magisk version name: e136fb3a
Magisk version code:  22102

I updated to the lastest version of LineageOS (migration from A10 to A11) and tried to reinstall magisk.
I try the "new way" and the "custom recovery" way (using TWRP). Both are shown as success but the boot image is unbootable.

I can't get any kernel logs nor adb logcat as the system doesn't reach debugging state.

**First try**

The system pass the Motorola logo after a longer time than usual then the LineageOS boot animation start. adb doesn't detect the device (debugging was enabled and authorized for the computer). The animation stay there for a really long time before the phone automatically reboot into the LineageOS recovery. That was the same regardless the installation method used (app+flashing or TWRP).

**Analyse with aboot**

Comparing the magisk boot image with the default one revealed some element that may explain something here : 
- The image size is different (magisk boot image is smaller even if it contain the magisk custom init, .backup and overlay.d directories)
```
< bootsize = 0x4000000
---
> bootsize = 0x16cd528
```
- Both kernel (zImage) are different for one byte
```
❯ cmp --print-bytes ../a/zImage ../b/zImage
../a/zImage ../b/zImage diffèrent: octet 12, ligne 1 is 133 [ 175 }
```
- No difference in the initrd (except for the magisk stuff like said earlier)

**Second try**

Because I read that boot image size should always be correct, I tried to repack the magisk boot image with the "correct" bootsize (using aboot). That test passed the Motorola logo but, after a short (2-3s) boot animation the phone reboot to recovery.

**Third try**

I tested will replacing the zImage (and the correct size) but that didn't get beyond the Morotola logo and rebooted to recovery.

At this point I just flashed back the default boot image for now.
NB1 : I always flashed the default boot image and do a clean system boot between each try.
NB2 : I also reinstalled LineageOS to be sure both slot where with Android 11

```
lake:/ $ cat /proc/mounts
/dev/root / ext4 ro,seclabel,relatime 0 0
tmpfs /dev tmpfs rw,seclabel,nosuid,relatime,size=1895336k,nr_inodes=473834,mode=755 0 0
devpts /dev/pts devpts rw,seclabel,relatime,mode=600 0 0
proc /proc proc rw,relatime,gid=3009,hidepid=2 0 0
sysfs /sys sysfs rw,seclabel,relatime 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
tmpfs /mnt tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755,gid=1000 0 0
tmpfs /mnt/installer tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755,gid=1000 0 0
tmpfs /mnt/androidwritable tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755,gid=1000 0 0
/dev/block/dm-0 /vendor ext4 ro,seclabel,relatime,discard 0 0
tmpfs /apex tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755 0 0
none /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
none /dev/cpuctl cgroup rw,nosuid,nodev,noexec,relatime,cpu 0 0
none /acct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct 0 0
none /dev/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent 0 0
none /dev/stune cgroup rw,nosuid,nodev,noexec,relatime,schedtune 0 0
tracefs /sys/kernel/tracing tracefs rw,seclabel,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,seclabel,relatime 0 0
none /config configfs rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/fuse/connections fusectl rw,relatime 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
adb /dev/usb-ffs/adb functionfs rw,relatime 0 0
tracefs /sys/kernel/debug/tracing tracefs rw,seclabel,relatime 0 0
/dev/block/bootdevice/by-name/modem_a /vendor/firmware_mnt ext4 ro,context=u:object_r:firmware_file:s0,nosuid,nodev,relatime 0 0
/dev/block/bootdevice/by-name/bluetooth_a /vendor/bt_firmware ext4 ro,context=u:object_r:bt_firmware_file:s0,nosuid,nodev,relatime 0 0
/dev/block/bootdevice/by-name/dsp_a /vendor/dsp ext4 ro,defcontext=u:object_r:adsprpcd_file:s0,seclabel,nosuid,nodev,relatime,data=ordered 0 0
/dev/block/bootdevice/by-name/persist /mnt/vendor/persist ext4 rw,seclabel,nosuid,nodev,noatime,no_sehash_xattr,data=ordered 0 0
/dev/block/bootdevice/by-name/fsg_a /vendor/fsg ext4 ro,context=u:object_r:fsg_firmware_file:s0,nosuid,nodev,relatime 0 0
/dev/block/bootdevice/by-name/userdata /data ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
tmpfs /linkerconfig tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755 0 0
/dev/block/loop6 /apex/com.android.tzdata@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop6 /apex/com.android.tzdata ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/bootdevice/by-name/userdata /data/user/0 ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
tmpfs /data_mirror tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=700,gid=1000 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_ce/null ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_ce/null/0 ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/data_de/null ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
/dev/block/bootdevice/by-name/userdata /data_mirror/cur_profiles ext4 rw,seclabel,nosuid,nodev,noatime,discard,nobarrier,noauto_da_alloc,resgid=1065,data=ordered 0 0
/dev/block/loop7 /apex/com.android.cellbroadcast@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop7 /apex/com.android.cellbroadcast ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop8 /apex/com.android.media.swcodec@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop8 /apex/com.android.media.swcodec ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop9 /apex/com.android.adbd@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop9 /apex/com.android.adbd ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop10 /apex/com.android.tethering@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop10 /apex/com.android.tethering ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop11 /apex/com.android.neuralnetworks@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop11 /apex/com.android.neuralnetworks ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop12 /apex/com.android.resolv@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop12 /apex/com.android.resolv ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop13 /apex/com.android.permission@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop13 /apex/com.android.permission ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop14 /apex/com.android.vndk.v30@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop14 /apex/com.android.vndk.v30 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop15 /apex/com.android.wifi@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop15 /apex/com.android.wifi ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop16 /apex/com.android.extservices@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop16 /apex/com.android.extservices ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop17 /apex/com.android.sdkext@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop17 /apex/com.android.sdkext ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop18 /apex/com.android.runtime@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop18 /apex/com.android.runtime ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop19 /apex/com.android.mediaprovider@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop19 /apex/com.android.mediaprovider ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop20 /apex/com.android.i18n@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop20 /apex/com.android.i18n ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop21 /apex/com.android.apex.cts.shim@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop21 /apex/com.android.apex.cts.shim ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop22 /apex/com.android.media@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop22 /apex/com.android.media ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop23 /apex/com.android.os.statsd@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop23 /apex/com.android.os.statsd ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop24 /apex/com.android.ipsec@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop24 /apex/com.android.ipsec ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop25 /apex/com.android.art@1 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop25 /apex/com.android.art ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop26 /apex/com.android.conscrypt@300000000 ext4 ro,dirsync,seclabel,nodev,noatime 0 0
/dev/block/loop26 /apex/com.android.conscrypt ext4 ro,dirsync,seclabel,nodev,noatime 0 0
tmpfs /storage tmpfs rw,seclabel,nosuid,nodev,noexec,relatime,size=1895336k,nr_inodes=473834,mode=755,gid=1000 0 0
/data/media /mnt/runtime/default/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/read/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/write/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/runtime/full/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/fuse /storage/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/installer/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/user/0/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/data/media /mnt/pass_through/0/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /storage/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/0/emulated/0/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/dev/block/vold/public:179,65 /mnt/media_rw/7D32-66B4 exfat rw,dirsync,nosuid,nodev,noexec,noatime,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,namecase=0,errors=remount-ro 0 0
/mnt/media_rw/7D32-66B4 /mnt/runtime/default/7D32-66B4 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6 0 0
/mnt/media_rw/7D32-66B4 /mnt/runtime/read/7D32-66B4 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/7D32-66B4 /mnt/runtime/write/7D32-66B4 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18 0 0
/mnt/media_rw/7D32-66B4 /mnt/runtime/full/7D32-66B4 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7 0 0
/dev/fuse /storage/7D32-66B4 fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/installer/0/7D32-66B4 fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/0/7D32-66B4 fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/user/0/7D32-66B4 fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/mnt/media_rw/7D32-66B4 /mnt/pass_through/0/7D32-66B4 sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=7 0 0
/dev/fuse /mnt/installer/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/androidwritable/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/dev/fuse /mnt/user/10/emulated fuse rw,lazytime,nosuid,nodev,noexec,noatime,user_id=0,group_id=0,allow_other 0 0
/data/media /mnt/pass_through/10/emulated sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/10/emulated/10/Android/data sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/androidwritable/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/user/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal,unshared_obb 0 0
/data/media /mnt/installer/10/emulated/10/Android/obb sdcardfs rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal,unshared_obb 0 0
```

**Comment by Tutul-** [comment]
@osm0sis Sorry for the ping but it's the second time the bot auto-close my issue saying that my Magisk version code isn't the latest (22102) but it's exactly what I wrote on the top of my issue :-/

Not sure why the bot close my issue on that. Is it possible to review and maybe reopen my issue ?

**Comment by bestouff** [comment]
Hi,
Same problem on a Oneplus 7T Pro (hotdog), here the boot image has the same size after patching but it still bootloops when flashed.

**Comment by osm0sis** [comment]
Do you have TWRP installed? Might be incompatible.

**Comment by Tutul-** [comment]
I only have the default recovery installed (with LineageOS) and it work perfectly when the boot crash.
I only access TWRP using `fastboot boot twrp-xxxxx.img`

**Comment by bestouff** [comment]
For my part, it's only stock LineageOS (OS + Recovery).

**Comment by bestouff** [comment]
Do you want me to upload `boot.img` and `magisk_patched.img` somewhere ? (100M each, but I made a 39M archive containing both)

**Comment by Gerii** [comment]
Same issue on Mi Mix (lithium). I do have TWRP installed though. Does not matter if installed via fastboot or TWRP.

**Comment by Tutul-** [comment]
Still happen after the latest canary release.

**Comment by MrHemlock** [comment]
Running into the same issue on my Pixel 2.  Tried similar methods as the original poster.  Have been trying it periodically with each new patch of LinageOS 18

**Comment by Ivy-Mike** [comment]
Running into the same issue on OnePlus 5T, latest 2021.05.04 patch.

**Comment by Tutul-** [comment]
The latest canary on the latest OTA update is still causing trouble.
I confirm that all of my modules are disabled (manually by touch modules/*/disabled)
As the default kernel doesn't seem to populate the required memory for /sys/fs/pstore/ I may need to try build one myself (it's strange because the default recovery from LineageOS does provide that directory with an empty file to read annotate-ramoops-0).

I don't have a full backup of my phone (and can't store a full one off it for now, so I can't try a full reset to see if that help :-/

**Comment by bestouff** [comment]
> I don't have a full backup of my phone (and can't store a full one off it for now, so I can't try a full reset to see if that help :-/

Ditto. I'm stuck with non-working apps because I can't become root and make a backup anymore :cry:

**Comment by osm0sis** [comment]
Okay, which OnePlus devices are affected, and what are your setups on them? Always Lineage, or also stock for some of you?

**Comment by Ivy-Mike** [comment]
Oneplus 5T for me ofc. Lineageos-18-1, the bootloop only happens after a lineageOS update, doesn't matter if official lineage recovery or twrp, need to wipe data for system to boot again. after any lineage 18.1 update and data wipe I can boot system and then reboot recovery and flash magisk. Now the system boots flawlessly with magisk. After next nighly lineageos-18-1 update same bootloop happens again. Tired of reinstalling my Phone, haha 🤣. Lineage os 17.1 works flawlessly.

**Comment by osm0sis** [comment]
Sounds like something weird with addon.d perhaps, I'll look into it on my 5T.

**Comment by bestouff** [comment]
7T Pro, didn't try wiping (can't backup, yes I know please don't shoot). LOS 18.1, bootloops with Magisk, works well without it.

**Comment by Tutul-** [comment]
I'm on Moto G7 Plus (not a OnePluse devise). It wasn't something with addon.d for me as I deleted the magisk script after the first failure to force a clean install of LineageOS 11 in the other slot. The problem still appear

**Comment by osm0sis** [comment]
That doesn't make sense. If you deleted the addon.d script then there is no Magisk at all in the other slot, so your problem is something different.

**Comment by Tutul-** [comment]
Well I did a clean installation of Magisk just after that to see if it was something related to the update process (both with the app and TWRP). It's literally what I describe in the bug report... ^^"

**Comment by osm0sis** [comment]
Okay so the difference is you just did it with the installer instead of addon.d

**Comment by Tutul-** [comment]
Well the upgrade to LineageOS 11 was with addon.d still present but Magisk just disapeard so I assumed that addon.d wasn't applied during major upgrade (10->11). I didn't try the data wipe because I don't have any up to date backup for the moment.

**Comment by Ivy-Mike** [comment]
Update: OnePlus 5T: My issue was an Lineage / Android google play issue, not an magisk issue. Adding link to lineage gitlab issue for users who might be in the same situation, sorry for the inconvenience.
Solved by:
1. Flash lineage nightly
2. Flash Magisk
3. Flash nikkagapps
4. reboot system.

If u reboot between any of the steps you will get bootloop

[https://gitlab.com/LineageOS/issues/android/-/issues/3460](url)

**Comment by bestouff** [comment]
I'm not sure, because I don't use gapps on my device, and it still fails.

**Comment by Tutul-** [comment]
me neither, the only flashed stuff are the update and Magisk

**Comment by cocka11** [comment]
Flash rom
Flash gapps
Flash magisk

**Comment by klic** [comment]
Same with LOS18.1 on FP3, Opengapps test build and magisk. Without magisk everything is fine, as soon as i boot the patched boot.img the LOS boot animation gets slow up to non moving, sometimes disappears. After some time the system reboots. Will try to attach a logcat

**Comment by Tutul-** [comment]
> 
> 
> Edit: logcat is[ here](https://lichtenwalder.name/typescript.txt)

Maybe can you share a logcat without magisk so it may be easier to compare and find what may be the source ?

**Comment by osm0sis** [comment]
Any luck with 23013? Some regressions have been fixed.

**Comment by osm0sis** [comment]
No response in 2 weeks so I'll presume fixed unless new logs and confirmation from 23014 are produced.

**Comment by Tutul-** [comment]
@osm0sis sorry for the delay but I wasn't really able to work on that for a couple of month :-(

I just tried with the latest canary version available today and still trouble to get a working system up.

But I'm not sure if it's still a bootloop or a stucked boot now...
After more than 5 minutes on the boot animation, I decided that the attempt was a failure and I reverted to a backup installation
