### ISSUE TITLE
Can not power off charging when installed Magisk between 16.4 to 17.2 at Android P

### ISSUE THREAD

**Issue by 10330384** [topjohnwu/Magisk#597]
Device: 
Google Pixel
Google Pixel XL
Google Pixel 2XL

Android build
PPR1.180610.009
PPR2.180905.005
Edit:
Turn the device off and put the charger on, device will show first charging icon forever and screen will never sleep even if remove the charger.
The only way to escape is long power key hold

**Comment by ThotSoft** [comment]
Upload log, let see how P got trouble around here.

**Comment by 10330384** [comment]
@ThotSoft  Thanks for getting back to me, but How or Where can i get power off log?

**Comment by fsrrt** [comment]
What

**Comment by ThotSoft** [comment]
I think there's no way to capture log when device is switch off, but I think your problem may be solvable with shutdown/startup log, I'm not a genius too so lets wait for someone, your problem is very rare and for me, its the first time i knew like this kind.

**Comment by zosxavius** [comment]
I can confirm. Its been that way since I tried with the 16.7 beta. Not a huge issue, but very annoying.

**Comment by julianp1958** [comment]
I didn't notice it until 17.0 but it may have been there. Definitely an issue and could (?) lead to screen burn.
Charging icon remains on screen even after disconnecting charge lead and takes 20 sec + power button hold to remove/restart.

**Comment by diluente** [comment]
Same problem on xiaomi mi A2 running android one 8.1 with latest security patch and magisk 17.1
When the phone is charging and i turn it off, it reboots itself and hangs on android one logo. Same if the phone is put in charge when turned off.

**Comment by topjohnwu** [comment]
This is fixed in latest builds

**Comment by 10330384** [comment]
Thank you for your fixing. It looks like no fixed yet.
Google Pixel 2 XL PPR2.181005.003 
Magisk Manager 6.0.1 V17.3
Still can not power off charging.

**Comment by Riptides** [comment]
I can confirm the problem still exists on V17.3 as well on my Pixel 2.
Magisk Manager v6.0.1 (151) with Magisk v17.3
Android build: PPR2.181005.003

Can provide any testing/logging if needed.

**Comment by Didgeridoohan** [comment]
@10330384 and @Riptides 

Magisk v17.3 is not the latest build. Have you tried the current Canary build (which happens to be [mandatory when reporting bugs](https://github.com/topjohnwu/Magisk#bug-reports))?

**Comment by ET714** [comment]
The problem also exists on my Essential PH-1 with Magisk V17.3 and Magisk Manager v6.01.

**Comment by Riptides** [comment]
@Didgeridoohan 
I have not, my apologies for missing that.

**Comment by jasoriab** [comment]
Duplicate issue here: https://github.com/topjohnwu/Magisk/issues/743

**Comment by jasoriab** [comment]
Pixel 2 XL - Problem solved with the November update of Google - 9.0.0 (PQ1A.181105.017.A1, Nov 2018)
Even with the stable version 17.1, it is possible now charge the phone when is powered off.

**Comment by 10330384** [comment]
Released version 18.0 is already fixed

**Comment by diluente** [comment]
not solved. keeps turning on and hangs on android logo
xiaomi MI A2 running android 9.0 and magisk 18.0
restoring stock boot image solves the problem

**Comment by 10330384** [comment]
It reproduce at PQ1A.181205.002, Dec 2018 Magisk v18.0

**Comment by bdashore3** [comment]
Can confirm

**Comment by CodingDinosaur** [comment]
Still occurring for me on Magisk 18.0 with stock ROM, Pixel 3 blueline PQ1A.181205.006
