### ISSUE TITLE
Magisk stable v25.1 stuck at splash screen

### ISSUE THREAD

**Issue by zputnyq** [topjohnwu/Magisk#6026]
Device: Xperia M4 E2306
Android version: stock 6.0.1
Magisk version name: 9183a0a6
Magisk version code: 25101 (D)

It's strange issue. Magisk v25.1 used to be the same as debug v25.1 despite its ability to handle logging.
Here is the chronology, the chonology is different to #5931
I updated magisk from v23.0 stable to debug v25.1 by direct installing & tried clean installing debug version as well. There was no problem, magisk app wasn't stuck. However when I switched the apk to stable then open the app it stuck at splash screen.
I had tried doing clean install of magisk stable v25.1, the same thing also happened, it stuck at splash screen. 

Here's anr file that I generate with this command
su -c kill -s SIGQUIT $(pidof com.topjohnwu.magisk)

[traces.txt](https://github.com/topjohnwu/Magisk/files/8966508/traces.txt)

**Comment by Tryfos** [comment]
> Device: Xperia M4 E2306 Android version: stock 6.0.1 Magisk version name: [9183a0a](https://github.com/topjohnwu/Magisk/commit/9183a0a6ea37ea7c43b86dd3f34a7ff505068a02) Magisk version code: 25101 (D)
> 
> It's strange issue. Magisk v25.1 used to be the same as debug v25.1 despite its ability to handle logging. Here is the chronology, the chonology is different to #5931 I updated magisk from v23.0 stable to debug v25.1 by direct installing & tried clean installing debug version as well. There was no problem, magisk app wasn't stuck. However when I switched the apk to stable then open the app it stuck at splash screen. I had tried doing clean install of magisk stable v25.1, the same thing also happened, it stuck at splash screen.
> 
> Here's anr file that I generate with this command su -c kill -s SIGQUIT $(pidof com.topjohnwu.magisk)
> 
> [traces.txt](https://github.com/topjohnwu/Magisk/files/8966508/traces.txt)

I have the same problem, updated to 25.1 from v.23 and now I'm stuck at splash screen. With a Lenovo Tab A10-70f.I also flashed with TWRP but nothing happens. The manager simply does not load. How can we downgrade?

**Comment by Nguyenson4989** [comment]
Same here.
SamSung galaxy note 9 SM-N960F.
Android 10.

**Comment by Kyliekyler** [comment]
Same here on my Realme 5i, got stuck on splash screen and cannot enter recovery. My Poco X3 on the other hand, booted but after first restart phone triggered ARP (Android Rescue Party) and the reported problem was `--reason=enablefilecrypto_failed`

**Comment by yujincheng08** [comment]
You submitted the wrong anr file.

**Comment by zputnyq** [comment]
> You submitted the wrong anr file. It should be named `trace_xx`

I don't think so.
The only trace file existed was only that.
I forgot to mention that after I executed the command my device was automatically rebooted. I had checked it before & the directory was empty.

**Comment by yujincheng08** [comment]
Please read the anr file. The commandline is `systemui`, not magisk.

**Comment by zputnyq** [comment]
> Please read the anr file. The commandline is `systemui`, not magisk.

Yes I know about it, I had opened & read the, that's the best I can do, I have tried a few times.
What strange is how can debug & stable release is different. Debug release isn't stuck while stable stuck. Another thing I notice is the placement of some files (back up of my stock boot.img & files in /sbin/.magisk/block). In stable release, back up of stock boot.img is placed on /data/adb/magisk while on debug it's in /data. In /sbin/.magisk/block for debug there's on 2 files data & system while stable it's more than 2.
I'm afraid something happen on the build process or the tools to build it & probably github website.
@topjohnwu

**Comment by fariborz4** [comment]
O

**Comment by doniedogawa** [comment]
I have same issue on LG V20 H990DS Android 8.0.

**Comment by pndwal** [comment]
This?:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-87128039

**Comment by zputnyq** [comment]
> This?: https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-87128039

Any other information ?
I had tested v25.2 stable & it still happens. It still stuck on splash screen aaas well.

**Comment by vincentwang0905** [comment]
Samsung J7(SM-J700F) same

**Comment by Kyliekyler** [comment]
> Samsung J7(SM-J700F) same

Try updating tho, the issue is from last year and has been fixed on my case

**Comment by MooneMan** [comment]
LG Aristo 2
Android: 8.1.0

Still having the same problem with 25.3 and 26.1

Works fine when I go back to 7.1.2

**Comment by pndwal** [comment]
> LG Aristo 2 Android: 8.1.0
> 
> Still having the same problem with 25.3 and 26.1
> 
> Works fine when I go back to 7.1.2

Do your Magisk (core binaries) and App match?

Eg you cannot load, or 'downgrade' to, 26100 App with 26101 Canary Magisk installed...

With 26101 Debug Magisk, daemon's version/signature checks are disabled and it should work however...

**Comment by MooneMan** [comment]
> > LG Aristo 2 Android: 8.1.0
> > Still having the same p> Do your Magisk (core binaries) and App match?
> 
> Eg you cannot load, or 'downgrade' to, 26100 App with 26101 Canary Magisk installed...
> 
> With 26101 Debug Magisk, daemon's version/signature checks are disabled and it should work however...

I tried the 26.1 debug (26101) apk and zip and still ended up stuck. I downgraded my manager back to 24.3 and it finally got past splash. There's no update button in the app now, though and if I try to direct install I end up back at 24300.

   
Notes:
Whenever I flashed the 26100 zip and try to open the 24.3 manager, tells me to get an update where it downloads then freezes on opening. It also does this with all three versions of the 26100 apks if I update that way.

It also did that when I use the update button in the 24300 manager to get to 26100 but keep the 24.3 zip installed. All three different way I can think of getting 26100 end up freezing.

I have also tried using 26100 zip and manager at the same time thinking the issue was caused by version differences, but the problem stayed.

However, my LG G6 H872 that only has Android 8.0 runs 26100 perfectly fine. It has arm64-v8a while the Aristos (two with the same problem) have armeabi-v7a, so it might be an issue with architecture.
