### ISSUE TITLE
Bootloop after ODIN flash (update)

### ISSUE THREAD

**Issue by RV7PR** [topjohnwu/Magisk#6230]
Device: Samsung Galaxy A53 (SM-A536B)
Android version: 12
Magisk version name: 38325e7
Magisk version code: 25203

[logs.zip](https://github.com/topjohnwu/Magisk/files/9451630/logs.zip)

![error](https://user-images.githubusercontent.com/17615589/187401961-72521d9c-ccde-4c6f-ae48-e7caa00ec2fd.jpg)

**Comment by Exynos-nibba** [comment]
make sure you patch the boot image in magisk manager through A53 itself. i.e install magisk manager on A53, patch the boot image and flash it. also what region is your phone from?

**Comment by RV7PR** [comment]
> make sure you patch the boot image in magisk manager through A53 itself. i.e install magisk manager on A53, patch the boot image and flash it. also what region is your phone from?

I have for the past 3 years with 2 different phones, never a problem. I use a usb flash drive to transfer de patched tar file and then flash with odin, i always check if file is corrupted. I'm using EUX, its the european union version

**Comment by nemesis03** [comment]
I probably have the same problem with my Samsung Galaxy S22. With the current firmware (S901BXXU2AVH9 EUX, security patch level 01.09.2022) I get a bootloop after flashing the patched firmware. I patched the firmware like I always do (transfer AP file via ADB patch on my S22, pull the patched file via ADB and then flash the complete firmware with the patched file instead of AP). I tried with magisk 25200 and 25203.
Flashing the old patched firmware (S901BXXU2AVG6, security patch level 01.08.2022) works and the phone boots normally

**Comment by Igetin** [comment]
In case it helps, I'm also using a Galaxy S22 from the same region, and I did a full **initial install** of Magisk with the same latest firmware (S901BXXU2AVH9 EUX), and did **not** experience any boot loops. So, if what you're exeriencing _is_ a bug or incompatibility issue with Magisk (and not an incorrect flashing procedure from the user), the problem is likely only related to upgrading the OS for an existing Magisk install.

One thing that came to my mind: the Odin release version might affect the results, so could you tell which version did you use, @nemesis03? I did the initial install with Odin v3.14.1 (original/unpatched).

**Comment by Exynos-nibba** [comment]
> > make sure you patch the boot image in magisk manager through A53 itself. i.e install magisk manager on A53, patch the boot image and flash it. also what region is your phone from?
> 
> I have for the past 3 years with 2 different phones, never a problem. I use a usb flash drive to transfer de patched tar file and then flash with odin, i always check if file is corrupted. I'm using EUX, its the european union version

did you flash the disabled vbmeta image? and seems like your device already has a version of twrp available, have you tried flashing magisk through twrp?

**Comment by SPYazdani** [comment]
Hi $contact_first_name $contact_last_name,
					    We've received your case $acase_name (# $acase_case_number) on $acase_date_entered
					    Status$acase_statusReference$acase_case_numberDescription$acase_description
On 05/09/2022, 03:02, ***@***.*** wrote:

make sure you patch the boot image in magisk manager through A53 itself. i.e install magisk manager on A53, patch the boot image and flash it. also what region is your phone from?

I have for the past 3 years with 2 different phones, never a problem. I use a usb flash drive to transfer de patched tar file and then flash with odin, i always check if file is corrupted. I'm using EUX, its the european union version

did you flash the disabled vbmeta image? and seems like your device already has a version of twrp available, have you tried flashing magisk through twrp?

**Comment by RV7PR** [comment]
I flashed patched tar created with magisk manager. then the boot got stuck and tried many times again without success so i flashed twrp to get logs and had to flash stock + wiping all data to boot again and after initial boot I flashed patched tar again for root and now it works but I did lose all my data.

**Comment by nemesis03** [comment]
I used an Odin v3.14.4 from somewhere, now I also tried Odin v3.14.1 (original and patched) from xda-developer forum. With these two version also the same result: bootloops with the newest firmware version.
I don't want to do a full wipe and will wait for the next firmware or a solution.
If this problem persists for future firmware updates we need some kind of fix, because a full data wipe with every firmware update is not very convenient.
In this issue (https://github.com/topjohnwu/Magisk/issues/6136) a user had a similar problem and solved it by removing the avb flags from the fstab. I did not try this yet, because I am not accustomed to patching the boot image manually, but I might try when I have some time. On the other hand I am not sure if this solves the problem, because I would expect this problem to persist even after a data wipe.

**Comment by nemesis03** [comment]
I just tried to update to the recent firmware (S901BXXS2AVHD) with magisk, but again bootloops.
Has anyone tried the update from a patched S901BXXU2AVH9 to a patched S901BXXS2AVHD without wiping all data?
Does anyoune have further information about manually patching the avb flags in the boot image?

**Comment by rajarshikhatua100** [comment]
same problem with my Samsung galaxy M31

**Comment by nemesis03** [comment]
I just tried an update to the latest firmware (S901BXXS2AVI7) and again had bootloops.
I even tried repatching the ramdisk with magiskboot with KEEPVERITY=false, but again bootloops. On the other hand I am not experienced with the process of manually patching with magiskboot.
Now I am back on the last working firmware from July.

@RV7PR @Igetin Did you manage to upgrade to newer magisk-patched firmwares without having to wipe the data partition?

Does anyone know how to disable KEEPVERITY in magisk without having to manually patch the files? I tried "echo KEEPVERITY=false>>/cache/.magisk" and "echo KEEPVERITY=false>>/data/.magisk", but that did not change anything.

Or any other idea why the bootloops happen and how to update to a newer firmware without having bootloops? Maybe @osm0sis has some ideas?

**Comment by Igetin** [comment]
> @RV7PR @Igetin Did you manage to upgrade to newer magisk-patched firmwares without having to wipe the data partition?

I haven’t tried yet, I’m still on the firmware S901BXXU2AVH9 relesed on August 31. I’ll try to find the time to test an upgrade next weekend.

**Comment by neoteche** [comment]
> Device: Samsung Galaxy A53 (SM-A536B) Android version: 12 Magisk version name: [38325e7](https://github.com/topjohnwu/Magisk/commit/38325e708e56129a4a31004628b4b8f1dd18ed3c) Magisk version code: 25203
> 
> [logs.zip](https://github.com/topjohnwu/Magisk/files/9451630/logs.zip)
> 
> ![error](https://user-images.githubusercontent.com/17615589/187401961-72521d9c-ccde-4c6f-ae48-e7caa00ec2fd.jpg)

I had the exact issue on my Samsung Galaxy A03

**Comment by nemesis03** [comment]
> Alright, I have now tried the upgrade for the Magisk-patched firmware, and I was able to **successfully** boot the new firmware after the flash. I upgraded from version S901BXXU2AVH9 to version S901BXXS2AVHD (EUX region). The user data is intact, and I did not have to perform a full wipe.

That sounds promising. I will probably do a full back up, then give it another try with the latest firmware (S901BXXU2BVJA, Android 13) and if that does not work wipe all data and restore from backup after upgrading to android 13. Might not be a bad idea to start with a wiped phone on android 13.

It still bothers me that there is no real solution to this problem...

**Comment by RV7PR** [comment]
Just did the upgrade with success with my Samsung Galaxy A53 (SM-A536B)
Went from: A536BXXU3AVGA Android 12  2022-08-26
To: A536BXXU4BVJG Android 13 2022-11-09

PS: I'm getting OTA updates from samsung even though my bootloader is unlocked and I'm rooted, you guys get them too?

**Comment by RV7PR** [comment]
Well.. I did use Magisk Bootloop Protector with patched boot image so I changed that to "basic function" (without patched boot image) just to be sure and then it worked but I'm not sure if it has anything to do with it.
@HuskyDG is it an possibility?

**Comment by nemesis03** [comment]
I finally solved this by wiping all my data. I did an upgrde to S901BXXU2BVJA (Android 13) and had bootloops. I then wiped the data and after that the device booted again. After setting up magisk I was able to upgrade to S901BXXU2BVKB without any issues. Unfortunately I had difficulties to restore my titanium backup, so I decided to downgrade to the last working firmware (S901BXXU2AVG6) and wipe data again. That was a bad decision, because I again was unable to update to a newer firmware. In the end I installed S901BXXS2AVHD and wiped data again, then restored my backups and then upgraded to S901BXXU2BVKB (Android 13) without issues.
So even a freshly setup S901BXXU2AVG6 was not able to upgrade.

> probably the cause of the problems could be some module, because I really uninstalled all after failing and then it worked.
I only use zygisk with safetynetfix. So in my case it was either safetynetfix or something entirely different

**Comment by hyperio546** [comment]
I solved this for my device by only flashing boot.img in AP slot in Odin. Rooted now.

**Comment by nettnikl** [comment]
Hi, i'm using a G975 (S10+) and experienced a similar boot loop without installing any update recently. Could this have the same cause as https://github.com/topjohnwu/Magisk/issues/6136?

**Comment by hyperio546** [comment]
> Hi, i'm using a G975 (S10+) and experienced a similar boot loop without installing any update recently. Could this have the same cause as https://github.com/topjohnwu/Magisk/issues/6136 (that nemesis mentioned also)?
> 
> Also @Igetin - you mentioned you successfully upgraded, did you ever experience a boot loop?
> 
> @hyperio546 - you just used the same patched boot.img?

I patched the boot.img of the new firmware and then flashed stock ap + bl + cp + home_csc and then boot.img separately.

**Comment by nettnikl** [comment]
@hyperio546 Thanks for the quick answer! So, just to confirm for dummys like me: So, you
 - had a rooted device
 - flashed a new firmware
 - had the boot loop
 - flashed stock ap + bl + cp + home_csc (keeping your data intact)
 - the boot loop was gone (or did you not try and restart then?)
 - patched boot.img with a recent magisk version on another, unrelated device
 - flashed the patched boot.img (keeping your data intact once again)
 - had a rooted, boot loop free system again

**Comment by hyperio546** [comment]
> @hyperio546 Thanks for the quick answer! So, just to confirm for dummys like me: So, you
>  - had a rooted device
>  - flashed a new firmware
>  - had the boot loop
>  - flashed stock ap + bl + cp + home_csc (keeping your data intact)
>  - the boot loop was gone (or did you not try and restart then?)
>  - patched boot.img with a recent magisk version on another, unrelated device
>  - flashed the patched boot.img (keeping your data intact once again)
>  - had a rooted, boot loop free system again

I did not have a bootloop. After flashing the stock firmware it seemed to boot and operate just fine. Then I flashed patched boot.img. I patched it on the same device before upgrading.

**Comment by nettnikl** [comment]
> I did not have a bootloop. After flashing the stock firmware it seemed to boot and operate just fine. Then I flashed patched boot.img. I patched it on the same device before upgrading.

It did not boot at all then, failing with the mentioned error message?

**Comment by hyperio546** [comment]
> > I did not have a bootloop. After flashing the stock firmware it seemed to boot and operate just fine. Then I flashed patched boot.img. I patched it on the same device before upgrading.
> 
> It did not boot at all then, failing with the mentioned error message?
> 

It booted. Flashing patched AP files bootlooped it.

**Comment by BlackMesa123** [comment]
If you haven't flashed a patched vbmeta image after unlocking your bootloader you **must** format your data partition in recovery mode in order to be able to boot again.

**Comment by nettnikl** [comment]
> you must format your data partition in recovery mode in order to be able to boot again

@BlackMesa123
Could you elaborate on that? I'm not an expert and would be very interested, under which circumstances you would say this is the case.

**Comment by coderx546** [comment]
> > you must format your data partition in recovery mode in order to be able to boot again
> 
> @BlackMesa123
> Could you elaborate on that? I'm not an expert and would be very interested, under which circumstances you would say this is the case.

It means that you gotta factory reset using the recovery.

**Comment by nettnikl** [comment]
Thanks for your answer! But let me clarify: which factor do you see, that makes that necessary? I'm trying to understand, whether thats also the case for me..

**Comment by BlackMesa123** [comment]
> Thanks for your answer! But let me clarify: which factor do you see, that makes that necessary? I'm trying to understand, whether thats also the case for me..

What actually happens is that the Keymaster TA will fail to verify the data partition encryption key at boot. This is what normally happens:

```
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_app_init:105) Start MDFPP keymaster version 4.4.08
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_app_init:109) Tl initialization done 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:834) ICCC os_patchlevel       : 369
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:835) ICCC boot_patchlevel     : 2417
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:836) ICCC vendor_patchlevel   : 2417
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1101) verified_boot_state : 2
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1102) device_locked       : 0
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1103) os_version          : 130000
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1111) os_patchlevel       : 202301
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1112) boot_patchlevel     : 20230101
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1113) vendor_patchlevel   : 20230101
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:131) verified_boot_key[32] : 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:138) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:146) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:131) verified_boot_hash[32] : 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:138) 6f b9 4c b4 38 ec 12 37 85 cd 53 2f a4 ce 8f c2 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:146) f7 68 c9 d2 74 a8 49 a0 b9 79 1c 2f 38 78 e9 7e 
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1118) warranty bit        : 1
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1119) trust boot status   : 1
01-14 23:37:17.405   688   688 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_configure() returns 0
01-14 23:37:17.419   688   688 W keymaster_tee: [WRN]begin req PARAMS: B32 P1 
01-14 23:37:17.422   688   688 D keymaster_swd: keymaster_swd [WRN] (swd_set_rot_integrity_status:346) Integrity broken state integrity_flag=0x6,lock_state=0,boot_state=2
01-14 23:37:17.422   688   688 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_begin() returns 0
01-14 23:37:17.424   688   688 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_update() returns 0
01-14 23:37:17.426   688   688 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_finish() returns 0
```

This is what happens when the key verification fails:

```
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_app_init:105) Start MDFPP keymaster version 4.4.08
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_app_init:109) Tl initialization done 
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (get_device_integrity_status:782) build_type : eng
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:834) ICCC os_patchlevel       : 369
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:835) ICCC boot_patchlevel     : 2417
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (get_root_of_trust_info:836) ICCC vendor_patchlevel   : 2417
02-14 11:55:25.781   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1101) verified_boot_state : 2
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1102) device_locked       : 0
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1103) os_version          : 130000
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1111) os_patchlevel       : 202301
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1112) boot_patchlevel     : 20230101
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1113) vendor_patchlevel   : 20230101
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:131) verified_boot_key[32] : 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:138) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:146) 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:131) verified_boot_hash[32] : 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:138) 65 8d be 7a 51 01 86 0f a1 5d 9c 02 e1 1c 1c b7 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (km_dump_hex:146) 35 b7 4b 48 59 72 29 98 39 9c ad 17 c7 bf cb ae 
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1118) warranty bit        : 1
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (tz_init_bootloader_info:1119) trust boot status   : 1
02-14 11:55:25.782   509   509 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_configure() returns 0
02-14 11:55:26.761   509   509 W keymaster_tee: [WRN]begin req PARAMS: B32 P1 
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (tz_check_oem:74) Device is compromized: fuse loc=5,status=0,sw_fuse_blown=1
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (aes_gcm_decrypt_finish:593) failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (handle_evp_error:554) Verification failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (aes256_gcm_decrypt:698) aes_gcm_decrypt_finish() failed. err = -30
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (tz_unwrap:226) tz_wrap_unwrap FAILED [-30]
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (swd_decrypt_ekey:341) km_unwrap() failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [WRN] (swd_decrypt_ekey:345) check with the legacy fallback for orange state
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (aes_gcm_decrypt_finish:593) failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (handle_evp_error:554) Verification failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (aes256_gcm_decrypt:698) aes_gcm_decrypt_finish() failed. err = -30
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (tz_unwrap:226) tz_wrap_unwrap FAILED [-30]
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (swd_decrypt_ekey:355) km_unwrap() failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [WRN] (swd_key_deserialize_ekey:461) swd_decrypt_ekey() failed
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (km_deserialize_key:284) Failed to deserialize key
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [ERR] (swd_begin:423) Failed with error: 4294967
02-14 11:55:26.765   509   509 D keymaster_swd: keymaster_swd [WRN] (swd_run_cb:254) swd_begin() returns -33
```

So the only way to boot again in your device is either by reflashing the stock binaries or formatting the data partition in recovery in order to generate a new data partition encrypt key.

**Comment by nettnikl** [comment]
Ah, i see. Thank you so much for your insightful descriptions and the example (kernel?) logs.
I think for me the issue might be different then, as i cannot find those log statements on my machine.

By the way, to everyone helping android newbies like me (as well as silent watchers), thank you very much, you're the reason projects like this are so appealing to newcomers!

**Comment by BlackMesa123** [comment]
> Ah, i see. Thank you so much for your insightful descriptions and the example (kernel?) logs.
> 
> I think for me the issue might be different then, as i cannot find those log statements on my machine.

I highly doubt that's the case, those are system logs since the keymaster service runs in system, not in kernel.

**Comment by coderx546** [comment]
> > Ah, i see. Thank you so much for your insightful descriptions and the example (kernel?) logs.
> > 
> > I think for me the issue might be different then, as i cannot find those log statements on my machine.
> 
> I highly doubt that's the case, those are system logs since the keymaster service runs in system, not in kernel.

You actually mean that flashing patched ap caused bootloops because of keymaster on my phone too?

**Comment by BlackMesa123** [comment]
> You actually mean that flashing patched ap caused bootloops because of keymaster on my phone too? 

As I've explained, yes. It's better to call this a boot failure since this is not a bootloop at all.

**Comment by coderx546** [comment]
> > You actually mean that flashing patched ap caused bootloops because of keymaster on my phone too? 
> 
> As I've explained, yes. It's better to call this a boot failure since this is not a bootloop at all.

Then how did flashing patched boot.img work and I typing this from my rooted phone?

**Comment by BlackMesa123** [comment]
> Then how did flashing patched boot.img work and I typing this from my rooted phone?

Your phone probably already has a patched vbmeta image in place. You don't have to format your data partition every time you flash new stuff, just when switching from a stock vbmeta img to a patched one (according to my tests).

**Comment by coderx546** [comment]
> > Then how did flashing patched boot.img work and I typing this from my rooted phone?
> 
> Your phone probably already has a patched vbmeta image in place, without it you shouldn't even be able to pass the bootloader screen. You don't have to format your data partition every time you flash new stuff, just when switching from a stock vbmeta img to a patched one (according to my tests).

I believe I am confused. The patched AP also has patched vbmeta and after flashing it I couldn't boot. But after flashing stock vbmeta inside of UNMODFIED AP and then flashing ONLY patched boot.img works. How??

**Comment by BlackMesa123** [comment]
> I believe I am confused. The patched AP also has patched vbmeta and after flashing it I couldn't boot. But after flashing stock vbmeta inside of UNMODFIED AP and then flashing ONLY patched boot.img works. How??

This is very strange. Normally the bootloader will refuse to load any image if the hashtree doesn't matches, so a patched vbmeta is required. This is a bootloader log from my phone (Galaxy A52s 5G) with a patched vbmeta:
```
avb_slot_verify.c:577: DEBUG: Loading vbmeta struct from partition 'vbmeta'.
{ 2531988 }[ ABL ] Load Image vbmeta total time: 1 ms 
{ 2532079 }[ ABL ] avb_vbmeta_image.c{ 2532110 }[ ABL ] :{ 2532110 }[ ABL ] 206{ 2532110 }[ ABL ] : ERROR: { 2532140 }[ ABL ] Hash does not match!
{ 2532171 }[ ABL ] avb_slot_verify.c{ 2532171 }[ ABL ] :{ 2532201 }[ ABL ] 638{ 2532201 }[ ABL ] : ERROR: { 2532232 }[ ABL ] vbmeta{ 2532232 }[ ABL ] : Error verifying vbmeta image: { 2532262 }[ ABL ] HASH_MISMATCH{ 2532262 }[ ABL ] 
avb_slot_verify.c:824: DEBUG: vbmeta: VERIFICATION_DISABLED bit is set.
```

Having some debug logs (last_kmsg) could help us understand why you are still able to boot with the old encrypt key even though you have installed a custom unsigned binary.

**Comment by coderx546** [comment]
> > I believe I am confused. The patched AP also has patched vbmeta and after flashing it I couldn't boot. But after flashing stock vbmeta inside of UNMODFIED AP and then flashing ONLY patched boot.img works. How??
> 
> This is very strange. Normally the bootloader will refuse to load any image if the hashtree doesn't matches, so a patched vbmeta is required. This is a bootloader log from my phone (Galaxy A52s 5G) with a patched vbmeta:
> ```
> avb_slot_verify.c:577: DEBUG: Loading vbmeta struct from partition 'vbmeta'.
> { 2531988 }[ ABL ] Load Image vbmeta total time: 1 ms 
> { 2532079 }[ ABL ] avb_vbmeta_image.c{ 2532110 }[ ABL ] :{ 2532110 }[ ABL ] 206{ 2532110 }[ ABL ] : ERROR: { 2532140 }[ ABL ] Hash does not match!
> { 2532171 }[ ABL ] avb_slot_verify.c{ 2532171 }[ ABL ] :{ 2532201 }[ ABL ] 638{ 2532201 }[ ABL ] : ERROR: { 2532232 }[ ABL ] vbmeta{ 2532232 }[ ABL ] : Error verifying vbmeta image: { 2532262 }[ ABL ] HASH_MISMATCH{ 2532262 }[ ABL ] 
> avb_slot_verify.c:824: DEBUG: vbmeta: VERIFICATION_DISABLED bit is set.
> ```
> 
> Having some debug logs (last_kmsg) could help us understand why you are still able to boot with the old encrypt key even though you have installed a custom unsigned binary.

How would I achieve that?

**Comment by BlackMesa123** [comment]
> How would I achieve that?

`adb shell su -c cat /proc/last_kmsg > last_kmsg`

At the end of the file there should be the current bootloader boot logs with every necessary info.

**Comment by coderx546** [comment]
> > How would I achieve that?
> 
> `adb shell su -c cat /proc/last_kmsg > last_kmsg`
> 
> At the end of the file there should be the current bootloader boot logs with every necessary info.
> 
> 

![Screenshot_20230215_152055_Termux.jpg](https://user-images.githubusercontent.com/96462198/218993455-538ba724-def0-46a7-9b7e-30d1828d3e6c.jpg)

Gives me no output!

**Comment by BlackMesa123** [comment]
The output has been printed inside the `last_kmsg` file of the directory you ran that cmd in. So it's stored in `/data/data/com.termux/files/home/last_kmsg`.

**Comment by coderx546** [comment]
> The output has been printed inside the `last_kmsg` file of the directory you ran that cmd in. So it's stored in `/data/data/com.termux/files/home/last_kmsg`.

[last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/10742111/last_kmsg.txt)
Done

**Comment by BlackMesa123** [comment]
> [last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/10742111/last_kmsg.txt) Done

Still can't find a reason why the AVB checks pass anyway even though you're using a patched Magisk kernel image. I did download your phone's firmware and tested myself and the check does fail indeed.

Stock kernel:
```zsh
➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
boot: Successfully verified sha256 hash of boot.img for image of 24666640 bytes
```

Magisk patched kernel:
```zsh
➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
Verifying image boot.img using embedded public key
vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
sha256 digest of boot.img does not match digest in descriptor
/home/mesa/bin/avbtool: Error verifying descriptor.
```

It might just be how libavb is implemented in your SoC's bootloader (not correctly lol), yours is a lucky case.

**Comment by coderx546** [comment]
> > [last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/10742111/last_kmsg.txt) Done
> 
> Still can't find a reason why the AVB checks pass anyway even though you're using a patched Magisk kernel image. I did download your phone's firmware and tested myself and the check does fail indeed.
> 
> Stock kernel:
> ```zsh
> ➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
> Verifying image boot.img using embedded public key
> vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
> boot: Successfully verified sha256 hash of boot.img for image of 24666640 bytes
> ```
> 
> Magisk patched kernel:
> ```zsh
> ➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
> Verifying image boot.img using embedded public key
> vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
> sha256 digest of boot.img does not match digest in descriptor
> /home/mesa/bin/avbtool: Error verifying descriptor.
> ```
> 
> It might just be how libavb is implemented in your SoC's bootloader (not correctly lol), yours is a lucky case.

Yeah even searching on yt for guides follows the exact this I did and it works. This phone is different.

**Comment by coderx546** [comment]
> > [last_kmsg.txt](https://github.com/topjohnwu/Magisk/files/10742111/last_kmsg.txt) Done
> 
> Still can't find a reason why the AVB checks pass anyway even though you're using a patched Magisk kernel image. I did download your phone's firmware and tested myself and the check does fail indeed.
> 
> Stock kernel:
> ```console
> ➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
> Verifying image boot.img using embedded public key
> vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
> boot: Successfully verified sha256 hash of boot.img for image of 24666640 bytes
> ```
> 
> Magisk patched kernel:
> ```console
> ➜  A035F_fw avbtool verify_image --image vbmeta.img --follow_chain_partitions
> Verifying image boot.img using embedded public key
> vbmeta: Successfully verified footer and SHA256_RSA4096 vbmeta struct in boot.img
> sha256 digest of boot.img does not match digest in descriptor
> /home/mesa/bin/avbtool: Error verifying descriptor.
> ```
> 
> It might just be how libavb is implemented in your SoC's bootloader (not correctly lol), yours is a lucky case.

Sorry for coming again after so long but I just remembered that this phone was distributed by the government in my state and was loaded with work policies. I wasn't possible to change the wallpaper too. So this phones is not a normal one.

**Comment by vvb2060** [comment]
https://github.com/topjohnwu/Magisk/blob/fe6b658c028e30f2972dd854b02ef2dd9a99d5b7/docs/install.md?plain=1#L126-L127

Nothing to do with Magisk.

**Comment by hyperio546** [comment]
> https://github.com/topjohnwu/Magisk/blob/fe6b658c028e30f2972dd854b02ef2dd9a99d5b7/docs/install.md?plain=1#L126-L127
> 
> Nothing to do with Magisk.

Exceptions exist. Not all phones are same.

**Comment by BlackMesa123** [comment]
> Exceptions exist. Not all phones are same. Also this is your problem because I have been hit with the exact same problem too.

As explained in https://github.com/topjohnwu/Magisk/issues/6230#issuecomment-1429639687 this is normal and has nothing to do with Magisk since it is not a bug. Your case is different because your phone boots normally with AVB enabled even though it **shouldn’t**, which means there’s a bug in your phone’s bootloader which can be fixed by Samsung anytime.

**Comment by BlackMesa123** [comment]
I also saw too late this was already noted in the install instructions, it may needs to be pointed out even better

https://github.com/topjohnwu/Magisk/blob/master/docs/install.md?plain=1#L115

**Comment by hyperio546** [comment]
> > Exceptions exist. Not all phones are same. Also this is your problem because I have been hit with the exact same problem too.
> 
> As explained in https://github.com/topjohnwu/Magisk/issues/6230#issuecomment-1429639687 this is normal and has nothing to do with Magisk since it is not a bug. Your case is different because your phone boots normally with AVB enabled even though it **shouldn’t**, which means there’s a bug in your phone’s bootloader which can be fixed by Samsung anytime.

I don't think that this is a bug. It shouldn't be able to boot into patched AP file because of hardware restrictions deep embedded into knox. As I pointed out before, its loaded with government knox policies. This is intended behaviour. 

But on the flip side yes its not related to Magisk.

**Comment by Kyogre** [comment]
Was same here with updating my S22 Exynos from S901BXXU4CWCG to S901BXXU5CWEA via Odin.
FYI. Before updating I have custom kernel (SLKernel) + Magisk 26.1 + system r/w patch applied via "afaneh92_lp_rw_tool_v0.4 r/w.zip"

After updating I also got this `android rescue party trigger fs_mgr_mount_all` error in TWRP log.

How I fixed bootloop without losing data:
1. Flashed normal twrp (twrp-3.7.0_12-1_afaneh92-r0s.tar in AP slot + vbmeta_disabled_R.tar in USERDATA slot).
2. Booted into TWRP > flashed afaneh kernel (r0s_kernel_5.10.136-afaneh92-g4bd352ee8905-dirty_2023_02_21.zip), so firmware could work with r/w system state.
3. Wiped cache + dalvik cache
4. And the most important part! In TWRP open terminal and execute `multidisabler` command. Wait till it finished.
5. Reboot to system.
And as I already said: you don't even need to format data.
