### ISSUE TITLE
Hiding and Restoring Magisk App not consistently working properly on many devices

### ISSUE THREAD

**Issue by DarkKnight1995** [topjohnwu/Magisk#6309]
Device: Samsung Galaxy A8 2018 (SM-A530F)
Android version: Android 9.0 (Stock Rom, Nov 2021 Security Patch)
Magisk version name: 38ab6858 (25203) (34) Canary + Debug
Magisk version code: 38ab6858 (25203) (34) Canary + Debug

So, as apparent from the title, I have been facing issues with hiding and restoring magisk app v25.x. I have clean installed my stock rom for these tests. I tried latest canary as well as debug build and these are the issues;

**CANARY VERSION**
For this version, when i first hide magisk app, the "settings" shortcut created begans to ask me of root permissions which when i grant it hides the magisk app and start magisk from the shortcut but it is now unable to detect zygisk status (says no even when active). I have to revoke the su permission i granted when the shortcut was being created, clear the app activity from recent apps list and then again start magisk from the shortcut but this time it works fine and will continue to work untill i try to restore the app.

Now, when i restore the magisk app, first it proceeds normally and then suddenly exits. After this, the magisk app is not restored and the shortcut is still there so i have to manually uninstall the "settings" shortcut and install the magisk apk to finally restore the app which brings back everything to normal.

THESE SAME ISSUES OCCUR WITH THE STABLE BUILD.

**DEBUG VERSION**
None of the issues i mentioned above occur in debug version, magisk app behaves normally.

**CONCLUSION**
I have gathered all the possible logs (magisk log, logcat during hiding restoring, bootlog, etc) for the canary as well as debug build. Kindly refer to them for detailed info. The file names are self explanatory. 

[DEBUG BUILD LOGS.zip](https://github.com/topjohnwu/Magisk/files/9720198/DEBUG.BUILD.LOGS.zip)
[CANARY BUILD LOGS.zip](https://github.com/topjohnwu/Magisk/files/9720200/CANARY.BUILD.LOGS.zip)

**Comment by pndwal** [comment]
Well done!

I've fielded countless examples of this/similar issue in XDA Magisk discussion thread, so know it's actually a widespread issue affecting many devices...

Here's a little strategy I posted re. Magisks failure to uninstall full app when taking "Hide the Magisk app", or failure to uninstall the stub app when taking "Restore the Magisk app" which also results in requests for SU permission, Magisk Installed = No, etc, etc:
https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/post-87044311

... It's not fixed...

**Comment by DarkKnight1995** [comment]
I also like to add that this failure to hide and restore occurs randomly. When the app fails to hide or restore the itself and then you try to do the same (hide or restore) immediately after the failure then it works normally. So, may be this issue occurs under a certain condition and that is unknown to me and many I suppose. I hope someone can figure this out soon.

**Comment by pndwal** [comment]
Same random occurrences observed... Successfully taking Hide the Magisk app (without any user intervention) occurs possibly less than 50% of the time for me...

Another issue, ie. failure to update App successfully in hidden state (we also end up with competing stub and full app), is probably much older but likely related and also occurs with a similar rate of failure...

I wasn't aware that this issue is absent in Debug builds... This could be a useful clue, especially if it happens to be linked to the strange failure of release-built Apps to open at all on certain devices while debug-built Apps (inexplicably) open without issue...

**Comment by Unknown78** [comment]
@pndwal @DarkKnight1995 
Hey guys, the issue and fix has been found, checkout the latest discussion of #6257.
It will be in the next magisk-release build I suppose.

**Comment by DarkKnight1995** [comment]
> @pndwal @DarkKnight1995 Hey guys, the issue and fix has been found, checkout the latest discussion of #6257. It will be in the next magisk-release build I suppose.

Don't know mate. My device is running stock android 9.0, kernel version: 4.4.111-22928167, I will wait for the next release to test it again with fresh os install. Untill then, debug build it is.

**Comment by pndwal** [comment]
> @pndwal @DarkKnight1995 Hey guys, the issue and fix has been found, checkout the latest discussion of #6257. It will be in the next magisk-release build I suppose.

This issue and yours (doesn't occur on my device, maybe Sammy, LG only?) are different although the cause may be related... Guess we need more testing here since https://github.com/topjohnwu/libsu/pull/140

**Comment by DarkKnight1995** [comment]
> 25205 was the last build where hiding worked correctly for me, can you try it? It's broken again currently so hopefully when that's fixed it'll work again for you.
> 
> Follow #6654 in the meantime.

Yes, I am using that build. Working fine.

**Comment by osm0sis** [comment]
Perfect. I'll mark this particular issue resolved then.

**Comment by pndwal** [comment]
> Perfect. I'll mark this particular issue resolved then.

Why do you think it's resolved?

I've just had the same symptoms moving back to Canary 25206 app (ie.app asking for su permission, dual apps remaining...) https://github.com/topjohnwu/Magisk/issues/6654#issuecomment-1450263736 ...

Often, hiding will work fine with one attempt but fail with another...

The thing is issues can be fixed by uninstalling duplicated apps w/ 25206 etc, so hidden App can still 'work fine' despite broken hiding routine... W/ new 25208 issue it seems nothing resolves it short of downgrading...

**Comment by osm0sis** [comment]
Because the creator of this issue says it works in 25205, so this issue is closed.

25208 has its own new hiding issue, which will be solved in the other issue.

**Comment by pndwal** [comment]
> Because the creator of this issue says it works in 25205, so this issue is closed.
> 
> 25208 has its own new hiding issue, which will be solved in the other open issue. No point in duplicated/stale issues.

Well it's not a stale issue and it is quite different to 25208 problem! 😜

I was very pleased to see this opened as it actually goes back at least as far as big 22.0 app hiding changes... I've been fielding basically the same issue regularly in XDA Magisk General Discussion thread since...

And, as I've said, it persists in 25206...

The nature of the issue means a user can't simply say 'it's fixed' without several hiding/unhiding attempts as it's not the hidden app that's failing, it's the hiding/unhiding process... As far as I can see, @DarkKnight1995 may simply have meant 25205 hidden App is working fine ATM...

Really, the issue titte should read/have been charged to  
'Hiding and Restoring Magisk App not consistently working properly many devices', but I doubt it was really fixed in 25205 even for Galaxy A8 2018 on Android 9...

Clearly the 25208 issue is more pressing/serious as the only workaround involves downgrading the app (which is fraught due to forceable downgrade prevention) to re-hide... Workaround for this is simply to locate the app Magisk failed to uninstall and do that manually...

Also, a fix for 25208 may foreseeably address both issues.

My feeling is that this issue should have been broadened and left open, but I'll wait to see how 25208 issue is resolved... If hiding/unhiding still fails to work consistently and this isn't re-opened after that I may make a fresh issue then... 🙃

**Comment by osm0sis** [comment]
🤷‍♂️

**Comment by pndwal** [comment]
> 🤷‍♂️

Good stuff, and thanks!... Hope 25209 release may resolve this along with 25208 issue...

**Comment by pndwal** [comment]
Sadly I can confirm that this issue still isn't fixed in 25209...

I wasn't able to update App with or without it hidden from 25206, so uninstalled that and installed 25209 manually after which I took Hide the Magisk app...

On the first attempt I got this:
![IMG_20230303_174354](https://user-images.githubusercontent.com/35104473/222654284-2bcd23fc-11e6-4dd5-9c3b-710c59fc741b.jpg)

As usual I ignored the message, closed the open App and after checking see that both full App and stub are installed... Stub data has in fact had data properly populated w/ Magisk binaries and after simply uninstalling he full App the hidden App works fine...

As before, Hide the Magisk app routine is simply failing to uninstall the full App after installing stub and populating it's data...

Also, as noted above, this is an inconsistent issue... With several subsequent attempts hiding succeeds without intervention, and with other attempts fails as described above...

**Comment by pndwal** [comment]
Interestingly, as with 25208, stub version (now v35) no longer shows when App is hidden using stub... I'm not sure if this is an intended change...

**Comment by AllenChangMusic** [comment]
It's to the point now where if I try and install one of the artifacts, it will self uninstall on me, so the app doesn't even open... Not sure if the fixes to this are making things worse? I'm on A14 DP1 P7P

**Comment by yujincheng08** [comment]
There's a race condiction when the release version of magisk is installing the hidden apk as root.

**Comment by pndwal** [comment]
> It's to the point now where if I try and install one of the artifacts, it will self uninstall on me, so the app doesn't even open... Not sure if the fixes to this are making things worse? I'm on A14 DP1 P7P

Intended behaviour due to certificate checking... You need to install Debug build to bypass this before installing a CI build... See https://github.com/topjohnwu/Magisk#signing-and-distribution

**Comment by yujincheng08** [comment]
Should have been fixed by https://github.com/topjohnwu/Magisk/commit/a1ce6f5f120b1ce61d567cbd1f89d66cd5cf36a2

Plz chk.

**Comment by pndwal** [comment]
Strangely there's still an issue but now it may resolve itself...

Updating the app while hidden to 25210 went fine (apart from the extra Momo detections 😉)...

Next I took Restore the Magisk app, then Hide the Magisk app and app handovers went fine for four cycles...

On the fifth attempt to Hide the Magisk app the app didn't reappear, so I found and opened the hidden stub app but Magisk failed to be detected:
![IMG_20230307_020342](https://user-images.githubusercontent.com/35104473/223153389-3576c55c-763b-4e68-848c-84fc48eb0de7.jpg)

Next I looked for and found a full app (hadn't been removed) and it too failed to detect Magisk:
![IMG_20230307_020228](https://user-images.githubusercontent.com/35104473/223157124-bf6d6a16-90c4-4606-83d4-cba6a0ae819c.jpg)

I closed the full app and opened the hidden stub app again, and was very surprised to see Magisk and Zygisk detected properly... I had not removed the full app as required previously:
![IMG_20230307_020510](https://user-images.githubusercontent.com/35104473/223155730-1d6ac444-6add-4e6d-9eed-ea75feca630d.jpg)

I then looked again for the full app and was surprised to find that it had now vanished!... Seems the hiding process had somehow frozen, and later decided to complete!? 🤔 ... So there was no need to intervene, but the delayed app removal is a puzzle...

Previously when a hide/restore process didn't finish I've had to manually uninstall a conflicting app...

Hope this assists your analysis...

**Comment by DarkKnight1995** [comment]
> Because the creator of this issue says it works in 25205, so this issue is closed.
> 
> 25208 has its own new hiding issue, which will be solved in the other open issue. No point in duplicated/stale issues.

Extremely sorry for the misleading info mate. I meant the debug build of 25205 (my bad). I haven't tried the later canary builds because of the hasle of going back and forth. Also I wasn't able to follow up because of some personal issue (life's not been treating me well for the last few weeks). Hope this clears it, issue is still there and it looks like this is not the case for just me.

**Comment by yujincheng08** [comment]
This issue should have been fixed. If anyone has issues with hiding Magisk App, they should be different issues. Feel free to open a new issue with logs.
