### ISSUE TITLE
Magisk Hide not working on MIUI 8.1.6 (Android 6.0 based) / MagiskSU not working in Titanium Backup

### ISSUE THREAD

**Issue by chaoscreater** [topjohnwu/Magisk#84]
Hi there,

I have 2 issues to report. One of them is very closely related to this one:
https://github.com/topjohnwu/Magisk/issues/44

I'm using a Redmi Note 3 Pro, clean flashed MIUI 8.1.6 (Android 6.0 based). Then flashed Magisk v11. Ran SafetyNet test and got a CTS profile mismatch.

If I do a clean flash of MIUI 8.0.6 (Android 5.1.1 based), flash Magisk v11 and run SafetyNet test, it passes and everything works...

I think the issue may be that it's unsupported on Android 6.0? If I do a clean flash of the ROM, install SuperSu v2.79, then install suhide v55, SafetyNet also fails.

I don't have any logs to attach as I am back on MIUI 8.0.6 (the working version). The logs don't show much either, so I didn't bother exporting them. Just thought I'd let you know anyway.

The other issue I'm reporting is that MagiskSU doesn't seem to work well with Titanium Backup. I can't freeze system apps. If I use SuperSu v2.79, I can freeze system apps no problem.

**Comment by Didgeridoohan** [comment]
A few questions:

- Does SafetyNet pass on a clean (no root or other mods) MIUI 8.1.6 (or 8.0.6 for that matter)? To test this one you'll need a locked bootloader (be careful that you can get back if something goes wrong) or a kernel not reporting the bootloader state, SELinux enforcing and possibly USB/ADB debugging disabled.
- Is it only CTS that fails? Do you pass basic integrity?
- Does Magisk Hide work otherwise? Test this by using a root checker. If it can detect root when not on the list and can't when it's added to the list Magisk Hide is working.

It could be that Hide is working as it should and it's that version of the ROM that just isn't CTS certification compatible...

The last issue about Titanium Backup is a known issue where some apps can't mount /system rw with MagiskSU 6. It's already fixed (https://github.com/topjohnwu/Superuser/commit/17923cabebaa4fafe3e5ec3129a25fc362cc1da9) and should be in the next release.

**Comment by chaoscreater** [comment]
Hi mate, thanks for the reply.

MIUI 8.0.6 clean flash + official unlocked bootloader + Magisk v11 works with SafetyNet. I haven't tried MIUI 8.1.6 with locked bootloader because of the hassle and the potential issue of bricking my phone etc. 

I'm not using custom kernels and I'm not using unofficial MIUI versions. USB/ADB is enabled (I use Titanium Backup and that's one of the requirements). I don't modify SeLinux and don't use any logon scripts. For all my testings, I've only setup MagiskSu. It is AFTER my testings that I start to install Xposed etc.

Tested Magisk Hide even when SafetyNet fails. Doesn't work unfortunately. I've also tested suhide on MIUI 8.1.6 and it doesn't hide.

I'm using SafetyNet Test from Google Play. The "response signature validation" is the part that fails. I'm not sure about the basic integrity check. I would check it had I not already restored to a TWRP backup. I should have taken notes on these things and I'm not really being helpful here, my apologies. 

I know it definitely works on MIUI 8.0.6 (Android 5.1.1 base). However, MagiskSU doesn't work with a lot of my apps (Titanium Backup being a critical one), so I kinda just gave up and reverted to my backup. I will test again properly and make notes and grab logs, once the new MagicSU is released.

**Comment by chaoscreater** [comment]
Just an update on this. I've managed to get the Titanium Backup issue sorted. However, I did not test this on my Redmi Note 3, I've tested this on my Galaxy S6 running 6.0 (which also has the same issue). The difference here is, SafetyNet passes on my S6 running 6.0, whereas it fails on my Redmi Note 3 (also running 6.0). SafetyNet passed in both Magisk Manager and also in the app "SafetyNet Test". 

Anyway, I could not freeze or restore apps in Titanium Backup (even though root is granted as shown in the app and in Magisk logs).

Use this to fix it (however, this may break Magisk Hide):
https://forum.xda-developers.com/apps/magisk/magisk-suxinbind-t3564673

**Comment by Didgeridoohan** [comment]
The Titanium Backup issue is not device specific, it's about MagiskSU. And, like I said earlier, it's been fixed in source and should be in the next release (v12?).

Meanwhile you could try the latest beta snapshot, it'll have the fix: https://forum.xda-developers.com/apps/magisk/unofficial-magisk-v10-beta-built-t3521901

**Comment by amarpreetosahan** [comment]
Sir, i am using Redmi Note 3 pro aka Kenzo a miui based mobile, I am on MIUI 8.1.2.0 based on Andriod 6.0.1, In Magisk V11. 1 Magisk Hide not worked as Both Basic Intergerty and CTS profile match are false, than I tried Clean Flash without any modification then basic intergrety passed but CTS profile are mismatch, further i want to mention here I tried old Magisk V9 with old Magisk Manager and PHH'S superuser than both basic intergrety and CTS profile are matched.... If you need more info you can ask me. 
Kindly look thanks.

**Comment by laggardkernel** [comment]
I am using Magisk 7. The titanium backup still failed to freeze apps.

**Comment by kapiljhajhria** [comment]
Same issue on redmi note 4 sd version

I don't need full safety net to be passed. Just need basic integrity to be true.
Should i give logs from magisk manager app or full log from some catlog app?
Also what do you want me to do while recording logs?

**Comment by kapiljhajhria** [comment]
My OS is MIUI8 based on android 6

**Comment by Redsandro** [comment]
Magisk (Manager) v12.0 here on Xiaomi Mi5 MIUI 8.3 7.4.6. First time I'm trying this so I might miss some inside knowledge, but I get the aforementioned message:

> SafetyNet Failed: CTS profile mismatch

Magisk Hide is turned on in settings. I also ran `sh /magisk/.core/magiskhide/enable` from `adb` just for fun.
